export const locales = ['ko', 'en'] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = 'ko';

// Native label per locale — surface in the language switcher so users see
// each language in its own script. Add a label here when introducing a new
// locale (alongside the entry in ``locales`` and the copy block below).
export const localeLabels: Record<Locale, { native: string; short: string }> = {
  ko: { native: '한국어', short: 'KO' },
  en: { native: 'English', short: 'EN' },
};

// ``ko`` is the canonical shape. Every other locale is typed as ``CopyShape``
// so missing keys surface as a TypeScript error at build time — adding a
// new language is a single mechanical pass with the compiler as a checklist.
const ko = {
    metadata: { description: '라즈베리파이를 위한 고성능 MCP 메모리 엔진', title: 'piLoci, AI가 스스로 기억하게 돕는 세컨드 브레인' },
    common: { brandName: 'piLoci', login: '로그인', signup: '시작하기', badge: 'Self-Hosted', copy: '복사', copied: '✓ 복사됨', cancel: '취소', confirm: '확인', processing: '처리 중...', loading: '로딩 중...', backToHome: '홈으로' },
    landing: {
      quotes: [
        '"기억은 지혜의 어머니이다" — 아이스킬로스',
        '"기억은 과거의 보물이자 미래의 길잡이다"',
        '"잊혀진 것은 존재하지 않는 것이나 같다" — 괴테',
        '"우리는 기억하는 만큼만 존재한다" — 파스칼',
        '"기억은 마음의 금고이다" — 토마스 풀러',
        '"과거를 기억하는 자만이 미래를 열 수 있다"',
        '"기억이 없으면 경험은 불가능하다" — 칸트',
        '"가장 위대한 재산은 기억이다" — 키티론',
        '"기억은 영혼의 그림자이다" — 호메로스',
        '"망각보다 기억이 더 많은 것을 만든다" — 벤자민 프랭클린',
        '"우리의 기억이 우리의 정체성이다" — 존 로크',
        '"기억은 시간의 파수꾼이다" — 에라스무스',
        '"잊지 않는 것은 곧 배우는 것이다"',
        '"기억은 모든 것의 어머니이자 보유자이다" — 아우구스티누스',
        '"좋은 기억은 지혜의 한 부분이다" — 세네카',
        '"기억 없는 마음은 거주자 없는 집과 같다"',
        '"과거를 기억하지 못하면 그것을 반복하게 된다" — 산타야나',
        '"기억은 경험의 창고이자 지혜의 원천이다"',
        '"가장 생생한 기억이 가장 깊은 상처를 남긴다"',
        '"망각은 자비이고, 기억은 축복이다"',
        '"기억은 지식의 보물이자 생각의 감독이다" — 키케로',
        '"모든 것은 기억에서 시작된다"',
        '"경험은 기억이라는 이름으로 살아간다"',
        '"기억하는 자는 결코 혼자가 아니다"',
        '"기억은 존재의 근원이다" — 마르셀 프루스트',
        '"기억이 강한 자는 삶도 강하다"',
        '"과거를 기억하는 것이 현재를 이해하는 길이다"',
        '"기억은 사랑의 가장 오래가는 증거이다"',
        '"배움은 기억의 또 다른 이름이다" — 플라톤',
        '"기억은 영원히 살아 숨쉬는 유일한 것이다"',
        '"기억은 잃어버린 시간을 되찾는 열쇠이다" — 프루스트',
        '"기억은 정체성의 핵심이다"',
        '"진정한 기억은 마음속에 새겨진다"',
        '"기억은 우리가 진정 누구인지 말해준다"',
        '"지혜는 기억의 결정체이다"',
        '"기억은 존재의 연속성이다" — 데이비드 흄',
        '"기억은 마음의 거울이다" — 톨스토이',
        '"기억 속에 사는 자는 죽지 않는다"',
        '"기억은 가장 충실한 친구이다" — 헨리 워드 비처',
        '"기억은 과거와 현재를 잇는 다리이다"',
        '"가장 소중한 것은 결코 잊히지 않는다"',
        '"기억은 경험을 지혜로 변환하는 연금술이다"',
        '"기억은 우리 모두의 내면의 서가이다" — 몽테뉴',
        '"좋은 기억력은 좋은 마음의 증거이다" — 아리스토텔레스',
        '"기억은 삶의 방아쇠이다" — 니체',
        '"기억이 있는 곳에 희망이 있다"',
        '"기억은 경험의 어머니이다" — 레오나르도 다빈치',
        '"과거를 기억하라, 그것이 미래의 밑거름이다" — 키케로',
        '"기억은 우리가 소유한 가장 영원한 소유물이다"',
        '"망각은 죽음이고, 기억은 부활이다" — 보들레르',
      ],
      titleLines: ['KNOWLEDGE MEMORY', 'FOR YOUR AI CORE'],
      descriptionLines: [
        'piLoci는 라즈베리파이와 같은 저전력 환경에서도 작동하도록 토큰, I/O, LLM 호출을 아끼는 MCP 기반 셀프 호스트 메모리 서버입니다.',
      ],
      terminal: {
        title: 'piLoci MCP',
        examples: [
          {
            q: '어제 진행했던 프로젝트 뭐였지?',
            tool: 'recall',
            toolArgs: '{"query": "어제 진행 프로젝트", "limit": 3}',
            result: 'preview 3개 — [piloci/스캐폴딩] [piloci/MCP 라우팅] [piloci/인증]',
            a: '어제 piLoci 프로젝트를 진행하셨습니다. MCP 서버 라우팅을 /mcp 프리픽스로 리팩토링하고, SSE 전송 레이어를 Starlette 서브앱으로 마운트하는 작업을 하셨네요.',
          },
          {
            q: '어디까지 했더라… 진행 상황 알려줘',
            tool: 'recall',
            toolArgs: '{"query": "현재 진행 상태", "limit": 5}',
            result: 'preview 5개 — 메모리 847개 중 관련 항목만 발췌',
            a: '현재 piLoci 프로젝트는 랜딩 페이지 UI 개선 중입니다. 다크 테마 violet 톤 적용, MCP 라우팅 /mcp로 리팩토링 완료. 다음: Docker 프로덕션 설정.',
          },
          {
            q: '그때 논의한 인증 방식 다시 알려줘',
            tool: 'recall',
            toolArgs: '{"query": "인증 auth 방식 토큰", "limit": 3}',
            result: 'preview 3개 — [auth 라우트] [2FA 설정] [토큰 스코프]',
            a: 'JWT 세션 + TOTP 2FA 이중 인증, argon2id 비밀번호 해시, API 토큰은 프로젝트 스코프 기반이었어요. refresh 토큰은 httpOnly 쿠키에 저장하기로 했습니다.',
          },
          {
            q: '저번에 읽다 만 책 제목이 뭐였지?',
            tool: 'recall',
            toolArgs: '{"query": "책 독서 목록 추천", "limit": 5}',
            result: 'preview 5개 — [독서 노트] [추천 도서] [완독 목록] [서재] [북클럽]',
            a: '"사피엔스"를 7장까지 읽으셨고, 그 다음으로 "Thinking, Fast and Slow"가 대기 중이었어요. 작년에 추천받은 "디에고 벨라스케스 평전"도 있네요.',
          },
          {
            q: '다음 주 미팅에 뭐 준비해야 하지?',
            tool: 'recall',
            toolArgs: '{"query": "미팅 회의 준비 agenda", "limit": 3}',
            result: 'preview 3개 — [주간 미팅] [스프린트 리뷰] [백로그]',
            a: '화요일 스프린트 리뷰: 랜딩 페이지 데모, Docker 배포 진행 상황 발표 예정이에요. 목요일 백로그 그루밍에서 v0.3 마일스톤 우선순위를 정하기로 했습니다.',
          },
          {
            q: '내가 어떤 커피 좋아하는지 알아?',
            tool: 'recall',
            toolArgs: '{"query": "커피 취향 맛 선호", "limit": 3}',
            result: 'preview 3개 — [취향 프로필] [카페 메모] [선물 리스트]',
            a: '산미 있는 라이트 로스트 선호, 특히 에티오피아 예가체프 종류를 좋아하세요. 블루보틀 싱글오리진이 단골이고, 설탕·시럽은 안 넣는 블랙파베리스타.',
          },
          {
            q: '오늘 장 봐야 할 거 리마인드 해줘',
            tool: 'recall',
            toolArgs: '{"query": "장보기 식료품 할 일", "limit": 5}',
            result: 'preview 5개 — [장보기 리스트] [레시피] [식단] [냉장고 재고] [할인]',
            a: '우유, 계란, 방울토마토, 아보카도가 떨어졌어요. 저번에 저장해둔 파스타 레시피로 올리브 오일도 사야 하고, 페스코 약속한 생선도 있네요.',
          },
          {
            q: '이번 프로젝트 제약사항 정리해줘',
            tool: 'recall',
            toolArgs: '{"query": "제약사항 constraints 보안", "limit": 5}',
            result: 'preview 5개 — [CLAUDE.md] [routes.py] [sse.py] [.env.example] [security]',
            a: '수집된 제약사항: ① argon2id만 사용 (bcrypt 금지) ② raw SQL 금지, ORM만 ③ JWT secret 환경변수로만 ④ (user_id, project_id) 필터 필수 ⑤ orjson 사용',
          },
          {
            q: '삼촌 생신이 언제였지? 선물 뭐 샀지?',
            tool: 'recall',
            toolArgs: '{"query": "삼촌 생신 선물 가족", "limit": 3}',
            result: 'preview 3개 — [가족 기념일] [선물 기록] [일정]',
            a: '삼촌 생신은 5월 12일이에요. 작년에는 몽블랑 만년필을 드렸고, 올해는 아직 정하지 않으셨어요. 3월에 보셨을 때 건강이 좀 안 좋으셨다고 했던 거 같아요.',
          },
          {
            q: '저번 여행 일정 다시 보여줘',
            tool: 'recall',
            toolArgs: '{"query": "여행 일정 계획 후쿠오카", "limit": 5}',
            result: 'preview 5개 — [여행 일정] [맛집 리스트] [숙소] [항공] [지출]',
            a: '후쿠오카 3박 4일: 1일차 텐진·야타이, 2일차 다자이후·운젠 온천, 3일차 하카타 구시탄·캐널시티. 숙소는 하카타역 도보 5분 호텔이었어요.',
          },
          {
            q: 'Docker 빌드가 자꾸 실패하는데 로그 확인해줘',
            tool: 'recall',
            toolArgs: '{"query": "Docker 빌드 에러 실패 로그", "limit": 3}',
            result: 'preview 3개 — [Dockerfile 수정] [CI 로그] [arm64 이슈]',
            a: '지난번에도 같은 문제가 있었어요. 멀티아키 빌드에서 arm64 타겟의 pip 캐시 레이어가 꼬이는 이슈였습니다. --no-cache로 빌드하니 해결됐었고요.',
            followUp: {
              q: '그때 수정했던 Dockerfile 내용 적용해줘',
              tool: 'memory',
              toolArgs: '{"action": "save", "content": "Dockerfile arm64 캐시 수정 사항 반영 완료", "tags": ["docker", "fix", "arm64"]}',
              result: '저장 완료 — Dockerfile arm64 빌드 수정',
              a: 'Dockerfile에 캐시 관련 수정 사항을 반영했습니다. 다시 빌드해볼까요?',
            },
          },
        ],
      },
      stats: {
        latency: '2ms',
        reduction: '80%+',
        uptime: '100%',
        latencyLabel: '벡터 검색',
        reductionLabel: '토큰 절감',
        uptimeLabel: '로컬 운영',
      },
      sections: {
        intro: {
          title: '소개',
          content: 'piLoci는 라즈베리파이와 같은 저전력 환경에서도 작동하도록 토큰, I/O, LLM 호출을 아끼는 MCP 기반 셀프 호스트 메모리 서버입니다.',
        },
        features: {
          title: '대화 속 핵심을 자동으로 분류하는 메모리',
          subtitle: [
            '대화는 자연스럽게 나누세요. 결정, 제약, 작업 흐름을 알아서 골라냅니다.',
            '임베딩은 LRU 캐시와 배치 처리로 아껴 쓰고, 검색은 요약부터 보여준 뒤 필요한 전문만 꺼냅니다.',
            '보관소 JSON은 디스크에 보관해 그래프와 내보내기를 매번 새로 만들지 않고, 정리된 필기장처럼 바로 펼칩니다.',
          ],
          list: [
            { title: '맥락 격리', desc: '프로젝트별 메모리 분리. 맥락 섞임 방지.' },
            { title: 'AST 기반 추출', desc: 'Tree-sitter로 코드 구조를 정밀하게 보존.' },
            { title: '2ms 벡터 검색', desc: 'Pi 5에서도 2ms 이내 시멘틱 검색.' },
            { title: '100% 로컬', desc: '클라우드 의존성 없이 외부 유출 걱정 없는 환경.' },
            { title: '자동 큐레이션', desc: '대화에서 핵심 정보를 자동 추출·저장.' },
            { title: '묶음 임베딩 수집', desc: '한 세션에서 추출된 메모리를 묶어서 임베딩해 Pi에서 실행 횟수를 줄임.' },
            { title: '미리보기 우선 검색', desc: '요약 먼저, 필요할 때만 전문 로드.' },
            { title: '보관소 작업공간', desc: '노트·그래프·태그를 디스크 캐시로 빠르게 재사용.' },
            { title: 'Telegram 요약', desc: '의미 있는 세션만 요약 전송.' },
            { title: '옵시디언 내보내기', desc: '캐시된 보관소를 zip으로 바로 내려받기.' },
            { title: 'MCP 표준 호환', desc: 'Claude, Cursor, Windsurf 등 바로 연결.' },
          ]
        },
        quickStart: {
          title: '빠른 시작',
          installTitle: '1. uvx를 이용한 설치',
          installDesc: '별도의 복잡한 설정 없이 다음 명령어로 즉시 서버를 실행할 수 있습니다.',
          setupTitle: '2. 백엔드 구성 (.env)',
          setupDesc: '환경 변수를 통해 SQLite 경로 및 인덱싱 엔진을 자유롭게 설정하세요.',
        },
        install: {
          uvEyebrow: '선행 설치 — uv',
          eyebrow: '설치',
          uninstallEyebrow: '삭제',
          recommendedLabel: '추천',
          setup: { title: 'uvx oc-piloci setup', desc: '' },
          install: { title: 'uvx oc-piloci install', desc: '' },
          uninstall: { label: '복사', cmd: 'uvx oc-piloci uninstall --yes' },
          platformsLabel: '지원 클라이언트',
          platformsHint: '',
          platforms: [
            { name: 'Claude Code', status: 'auto' },
            { name: 'OpenCode', status: 'auto' },
            { name: 'Cursor', status: 'auto' },
            { name: 'Gemini CLI', status: 'auto' },
            { name: 'Windsurf', status: 'auto' },
            { name: 'Codex CLI', status: 'auto' },
            { name: 'AntiGravity', status: 'auto' },
            { name: 'Zed', status: 'auto' },
            { name: 'ChatGPT Desktop', status: 'manual' },
          ],
          statusLabels: { auto: '자동', manual: '수동' },
        },
        capabilities: {
          title: '반드시 필요한 툴만, 극한의 미니멀리즘',
          desc: 'LLM의 프롬프트 맥락을 해치지 않도록, 최소한의 툴 개수로 최대한의 효율을 추구합니다.',
          note: 'LLM의 프롬프트 맥락을 해치지 않도록, 최소한의 툴 개수로 최대 효율을 추구합니다.',
          list: [
            { name: 'memory', desc: '새로운 정보나 프로젝트의 맥락을 영구 메모리에 저장하거나 오래된 항목을 제거합니다.' },
            { name: 'recall', desc: '기본은 preview만 반환하고, 필요할 때만 선택적으로 전문이나 markdown export를 가져옵니다.' },
            { name: 'listProjects', desc: '5분 캐시된 프로젝트 목록을 빠르게 가져오고, 필요하면 refresh=true로 강제 갱신합니다.' },
          ]
        },
        curation: {
          title: '대화가 끝나면 핵심이 정리되어 있습니다',
          eyebrow: '자동 증류와 분류',
          paragraphs: [
            'piLoci는 사용자가 저장 버튼을 누르길 기다리는 메모장이 아닙니다. 로컬 LLM이 대화 원문을 읽고 결정·제약·취향·작업 흔적을 추출합니다.',
            '겹치는 내용은 합치고, 프로젝트 단위로 태그와 노트로 묶어 정리합니다. 나중에 필요할 때 바로 꺼낼 수 있게 해둡니다.',
          ],
          stages: [
            { label: '대화 원문', desc: 'RawSession에 흐름을 남깁니다.' },
            { label: '자동 선별', desc: 'curator가 오래 남길 내용을 고릅니다.' },
            { label: '기억 그래프', desc: '노트와 태그를 연결된 지식으로 보여줍니다.' },
          ],
          graphTitle: '자동으로 작성되는 기억 그래프',
          graphDesc: '프로젝트의 결정, 제약, 취향, 작업 흔적이 하나의 별자리처럼 연결됩니다.',
          graphNodes: {
            project: { label: '프로젝트', value: 'piLoci' },
            decision: { label: '결정', value: '로컬 퍼스트' },
            curated: { label: '선별된 기억', value: '알아서 정리한 맥락' },
            constraint: { label: '제약', value: 'Pi 5 예산' },
            preference: { label: '취향', value: '클라우드 유출 없음' },
          },
        },
        pricing: {
          title: '투명한 오픈소스, 완전한 자유',
          desc: [
            'piLoci는 모든 소스코드가 공개된 오픈소스 프로젝트입니다.',
            '누구나 함께 참여하고 개선할 수 있습니다.',
          ],
          features: [
            '무제한 프로젝트 생성',
            '로컬 SQLite + LanceDB',
            '상업적 이용 가능 (MIT)',
            '개인 정보 추적 0%',
            '옵시디언 호환 워크스페이스',
            '팀 단위 멀티유저 지원',
            '완전한 셀프 호스트 (Docker)',
            'Google OAuth + TOTP 2FA',
          ],
          engineering: {
            title: '놀고 있는 라즈베리파이에게 맡기세요!',
            desc: '모든 아키텍처 결정은 "제로 코스트, 최소 리소스"를 기준으로 내려졌습니다.',
            items: [
              { label: 'LanceDB', desc: '클라우드 벡터 DB 불필요. 로컬 파일 기반 임베딩 저장소.' },
              { label: 'SQLite', desc: '외부 RDBMS 없이 모든 메타데이터를 로컬에서 처리.' },
              { label: 'fastembed (ONNX)', desc: 'GPU·torch 없이 CPU만으로 384차원 임베딩 생성.' },
              { label: 'LRU 임베딩 캐시', desc: '동일 텍스트 재연산 방지. 반복 쿼리는 즉시 반환.' },
              { label: '묶음 임베딩 수집', desc: 'curator worker가 추출 메모리를 한 번에 임베딩해 저전력 CPU에서 호출 수를 줄인다.' },
              { label: '미리보기 우선 검색', desc: '긴 검색 결과를 바로 모델에 쏟아붓지 않고 미리보기→불러오기→파일로 단계적으로 로드.' },
              { label: 'orjson', desc: '표준 json 대비 2-3배 빠른 직렬화. Pi의 느린 CPU에서 유의미.' },
              { label: '텔레그램 세션 요약', desc: '백엔드 메타데이터만으로 긴 작업 세션만 골라서 알림. LLM 토큰 추가 소모 0.' },
              { label: '캐시된 보관소 내보내기', desc: 'vault.json을 디스크에 캐시하고 옵시디언형 zip을 즉시 생성.' },
            ],
          },
        }
      },
      footer: '© piLoci 2026. Husband of Rebekah.',
      pending: { title: 'piLoci 불러오는 중', desc: '세션과 화면 상태를 확인한 뒤 바로 이동합니다.' },
    },
    privacy: {
      title: '개인정보 처리방침',
        subtitle: 'piLoci 개인정보 처리방침',
        preamble: '정보통신망 이용촉진 등에 관한 법률 등 관련 법률에 의한 개인정보 보호규정 및 가이드라인을 준수하고 있습니다.',
        sections: [
          {
            title: '1. 개인정보의 수집 항목',
            content: '원활한 서비스 이용과 고객과의 소통을 위해 수집합니다.',
            items: ['필수항목: 이메일', '자동수집항목: 활동 기록(감사 로그), 쿠키 등', '활동 기록이란? 로그인 시점, API 호출 기록, 프로젝트 생성/수정 이력 등이 포함되는 사용자 로그입니다.'],
          },
          {
            title: '2. 개인정보 보유 및 이용기간',
            content: '',
            items: ['가입 회원정보는 탈퇴 시 즉시 파기됩니다.', '프로젝트 데이터 및 메모리는 사용자가 직접 삭제할 때까지 보관됩니다.', '감사 로그는 계정 활성 상태 동안 보관됩니다.'],
          },
          {
            title: '3. 개인정보의 수집·이용 목적',
            content: '',
            items: [
              '이메일: 회원 가입 시 사용자 확인, 중복 가입 방지, 부정 이용 방지',
              '비밀번호: Argon2id 해시로 단방향 암호화하여 저장하며, 원문은 수집하지 않습니다.',
              '활동 기록, 접속 기록: 부정 이용 방지, 비인가 사용 방지, 서비스 품질 개선',
            ],
          },
          {
            title: '4. 개인정보의 제3자 제공',
            content: '',
            items: ['piLoci는 로컬 우선(Local-first) 철학에 따라 모든 데이터를 사용자의 장치에만 저장합니다.', '어떠한 개인정보도 외부 서버나 제3자에게 전송하지 않습니다.', '클라우드 동기화 기능 사용 시에만 사용자가 명시적으로 선택한 데이터가 전송됩니다.'],
          },
          {
            title: '5. 개인정보의 파기',
            content: '',
            items: ['회원 탈퇴 시 즉시 모든 개인정보를 파기합니다.', '비밀번호는 해시 형태로만 저장되므로 복원할 수 없습니다.', '서비스 종료 시 모든 사용자 데이터를 영구 삭제합니다.'],
          },
          {
            title: '6. 개인정보 보호를 위한 기술적·관리적 조치',
            content: '',
            items: ['비밀번호: Argon2id 단방향 해시 암호화', '인증: JWT 기반 세션 관리', 'API 접근: 프로젝트별 격리된 스코프 토큰', '네트워크: HTTPS/TLS 암호화 통신', '데이터베이스: 사용자·프로젝트 단위 접근 제어'],
          },
          {
            title: '7. 이용자의 권리',
            content: '',
            items: ['언제든지 본인의 개인정보를 열람·수정·삭제할 수 있습니다.', '서비스 내 설정 페이지에서 직접 관리 가능합니다.', '개인정보 처리에 대한 문의는 이메일로 연락 주시면 즉시 처리합니다.'],
          },
        ],
        dates: '공고일자: 2026년 1월 1일 / 시행일자: 2026년 1월 1일',
      },
    terms: {
      title: '서비스 약관',
      subtitle: 'piLoci 서비스 이용약관',
      preamble: '본 약관은 piLoci 서비스의 이용 조건과 절차, 이용자와 운영자의 권리·의무 및 책임사항을 규정합니다.',
      sections: [
        {
          title: '1. 약관의 적용',
          content: '',
          items: [
            '본 약관은 piLoci 서비스를 이용하는 모든 사용자에게 적용됩니다.',
            '운영자는 약관을 변경할 수 있으며, 변경 시 서비스 내 공지사항으로 안내합니다.',
            '변경된 약관에 동의하지 않을 경우 서비스 이용을 중단할 수 있습니다.',
          ],
        },
        {
          title: '2. 서비스 내용',
          content: '',
          items: [
            'piLoci는 AI 대화 맥락을 프로젝트 단위로 저장·검색·관리하는 자가호스팅 메모리 서비스입니다.',
            '핵심 기능: 대화 증류(자동 핵심 추출), 시맨틱 검색, 프로젝트 격리 메모리, MCP 도구 인터페이스.',
            '서비스 내용은 기능 개선을 위해 변경될 수 있으며, 주요 변경 시 사전 공지합니다.',
          ],
        },
        {
          title: '3. 사용자 의무',
          content: '',
          items: [
            '타인의 계정을 무단으로 사용해서는 안 됩니다.',
            '서비스의 보안 취약점을 악용하거나 시스템에 부하를 주는 행위를 금지합니다.',
            '저장하는 대화 콘텐츠에 대해 사용자가 전적인 책임을 집니다.',
          ],
        },
        {
          title: '4. 데이터 소유권',
          content: '',
          items: [
            '사용자가 입력하고 생성된 모든 데이터의 소유권은 사용자에게 있습니다.',
            '운영자는 사용자 동의 없이 데이터에 접근하거나 활용하지 않습니다.',
            '로컬 우선(Local-first) 구조에서 데이터는 사용자 장치에 저장됩니다.',
          ],
        },
        {
          title: '5. 서비스 중단 및 종료',
          content: '',
          items: [
            '운영자는 서비스 개선을 위해 일시적으로 서비스를 중단할 수 있습니다.',
            '서비스 종료 시 최소 30일 전에 공지하며, 사용자에게 데이터를 내보낼 기회를 제공합니다.',
            '사용자는 언제든지 계정을 삭제하고 모든 데이터를 즉시 파기할 수 있습니다.',
          ],
        },
        {
          title: '6. 책임의 한계',
          content: '',
          items: [
            '자가호스팅(Self-hosted) 서비스로서, 시스템 운영 및 데이터 백업의 책임은 배포자에게 있습니다.',
            'AI가 생성하는 증류 결과의 정확성에 대해 보장하지 않습니다.',
            '불가항력적 사유로 인한 서비스 중단에 대해서는 책임을 지지 않습니다.',
          ],
        },
      ],
      dates: '공고일자: 2026년 1월 1일 / 시행일자: 2026년 1월 1일',
    },
    admin: {
      eyebrow: '관리자 콘솔',
      title: '사용자 관리',
      description: '사용자 계정을 관리합니다.',
      filterAll: '전체',
      filterPending: '대기',
      filterApproved: '승인',
      filterRejected: '거부',
      filterInactive: '비활성',
      emptyMessage: '해당 상태의 사용자가 없습니다.',
      approve: '승인',
      reject: '거부',
      rejectReasonLabel: '거부 사유',
      rejectReasonPlaceholder: '거부 사유를 입력하세요',
      rejectConfirm: '거부 확인',
      cancel: '취소',
      status: { pending: '대기', approved: '승인됨', rejected: '거부됨' },
      reviewedAt: '처리일',
      noReviewer: '—',
      oauthProvider: '소셜',
      createdAt: '가입일',
      lastLogin: '마지막 접속',
      neverLoggedIn: '접속 기록 없음',
      confirmReject: '이 사용자의 가입을 거부하시겠습니까?',
      emailLabel: '이메일',
      statusLabel: '상태',
      actionLabel: '작업',
      loadError: '사용자 목록을 불러올 수 없습니다',
      retry: '다시 시도',
      emptyPending: '가입 대기 중인 사용자가 없습니다',
      promoteAdmin: '관리자로 승격',
      demoteAdmin: '관리자 권한 해제',
      activateUser: '계정 활성화',
      deactivateUser: '계정 비활성화',
      deleteUser: '사용자 삭제',
      deleteConfirmTitle: '사용자 삭제',
      deleteConfirmMessage: '이 사용자의 계정과 모든 데이터를 삭제합니다. 되돌릴 수 없습니다.',
      deleteConfirm: '삭제',
      // Toast messages — caller replaces {email} at use site.
      toastApproved: '{email} 승인됨',
      toastRejected: '{email} 거부됨',
      toastDeleted: '{email} 삭제됨',
      toastPromoted: '{email} 관리자로 승격됨',
      toastDemoted: '{email} 관리자 권한 해제됨',
      toastActivated: '{email} 활성화됨',
      toastDeactivated: '{email} 비활성화됨',
      twoFactor: '2FA',
      enabled: '사용 중',
      disabled: '꺼짐',
      adminBadge: '관리자',
      inactiveBadge: '비활성',
      searchPlaceholder: '이메일 또는 이름 검색...',
      confirmPromote: '이 사용자를 관리자로 지정하시겠습니까?',
      confirmDemote: '이 사용자의 관리자 권한을 해제하시겠습니까?',
      confirmDeactivate: '이 계정을 비활성화하시겠습니까?',
      confirmActivate: '이 계정을 활성화하시겠습니까?',
      you: '(나)',
      statsTotal: '전체',
      statsPending: '대기 중',
      statsAdmins: '관리자',
    },
    signup: {
      approvalTitle: '가입 완료',
      approvalMessage: '관리자 승인 후 이용할 수 있습니다.',
      approvalSubmessage: '승인 완료 시 로그인이 가능합니다.',
      goToLogin: '로그인으로 이동',
      title: '회원가입',
      subtitle: 'piLoci 계정을 만드세요',
      nameLabel: '이름',
      namePlaceholder: '홍길동',
      emailLabel: '이메일',
      passwordLabel: '비밀번호',
      passwordHint: '12자 이상, 대소문자 + 숫자 포함',
      confirmPasswordLabel: '비밀번호 확인',
      submitting: '가입 중...',
      submit: '가입하기',
      or: '또는',
      hasAccount: '이미 계정이 있으신가요?',
      loginLink: '로그인',
      validation: {
        nameMin: '이름은 2자 이상이어야 합니다',
        emailInvalid: '유효한 이메일을 입력하세요',
        passwordMin: '비밀번호는 12자 이상이어야 합니다',
        passwordUpper: '대문자 포함 필요',
        passwordLower: '소문자 포함 필요',
        passwordDigit: '숫자 포함 필요',
        confirmRequired: '비밀번호 확인을 입력하세요',
        confirmMismatch: '비밀번호가 일치하지 않습니다',
      },
      error: {
        emailDuplicate: '이미 사용 중인 이메일입니다',
        generic: '회원가입 중 오류가 발생했습니다',
      },
    },
    login: {
      approvalPending: '관리자 승인 대기 중입니다. 승인 완료 후 로그인할 수 있습니다.',
      approvalRejected: '가입 요청이 거부되었습니다. 관리자에게 문의해 주세요.',
      approvalPendingShort: '관리자 승인 대기 중입니다',
      approvalRejectedShort: '가입 요청이 거부되었습니다',
      title: '로그인',
      subtitle: '프로젝트 워크스페이스에 접속하세요',
      emailLabel: '이메일',
      passwordLabel: '비밀번호',
      submitting: '인증 중...',
      submit: '로그인',
      or: '또는',
      forgotPassword: '비밀번호를 잊으셨나요?',
      noAccount: '계정이 없으신가요?',
      signupLink: '가입하기',
      resetNotice: '비밀번호가 변경되었습니다. 새 비밀번호로 로그인해 주세요.',
      validation: {
        emailInvalid: '유효한 이메일을 입력하세요',
        passwordRequired: '비밀번호를 입력하세요',
      },
      error: {
        locked: '계정이 잠겼습니다',
        invalidCredentials: '이메일 또는 비밀번호가 올바르지 않습니다',
        oauthCancelled: '소셜 로그인이 취소되었습니다. 다시 시도해 주세요.',
        oauthExpired: '로그인 요청이 만료되었거나 유효하지 않습니다. 다시 시도해 주세요.',
        oauthFailed: '소셜 로그인 처리 중 오류가 발생했습니다. 다시 시도해 주세요.',
      },
    },
    forgotPassword: {
      title: '비밀번호 찾기',
      subtitle: '가입한 이메일을 입력하시면',
      subtitle2: '재설정 토큰을 발급해드립니다',
      emailLabel: '이메일',
      sentMessage: '재설정 토큰이 발급되었습니다.',
      sentMessage2: '아래 버튼으로 비밀번호를 변경하세요.',
      resetLink: '비밀번호 재설정하기',
      submitting: '전송 중...',
      submit: '재설정 토큰 받기',
      backToLogin: '로그인으로 돌아가기',
      validation: {
        emailInvalid: '유효한 이메일을 입력하세요',
      },
      error: {
        generic: '요청 중 오류가 발생했습니다',
      },
    },
    resetPassword: {
      title: '비밀번호 재설정',
      subtitle: '새 비밀번호를 입력하세요',
      tokenLabel: '재설정 토큰',
      tokenPlaceholder: '토큰을 붙여넣으세요',
      newPasswordLabel: '새 비밀번호',
      confirmPasswordLabel: '비밀번호 확인',
      passwordHint: '12자 이상, 대소문자 + 숫자 포함',
      submitting: '변경 중...',
      submit: '비밀번호 변경',
      backToLogin: '로그인으로 돌아가기',
      loading: '로딩 중...',
      validation: {
        tokenRequired: '토큰을 입력하세요',
        passwordMin: '비밀번호는 12자 이상이어야 합니다',
        passwordUpper: '대문자 포함 필요',
        passwordLower: '소문자 포함 필요',
        passwordDigit: '숫자 포함 필요',
        confirmRequired: '비밀번호 확인을 입력하세요',
        confirmMismatch: '비밀번호가 일치하지 않습니다',
      },
      error: {
        generic: '재설정 중 오류가 발생했습니다',
      },
    },
    settings: {
      eyebrow: '컨트롤 센터',
      title: '설정',
      description: '계정 및 보안 설정을 관리합니다',
      tabs: { account: '계정', security: '보안', tokens: '토큰', llm: 'LLM', data: '데이터', audit: '활동', mcp: 'MCP' },
      pending: {
        loadingTitle: '설정 불러오는 중',
        loadingDesc: '세션이 복원되면 계정 및 보안 설정을 이어서 표시합니다.',
        redirectTitle: '로그인 화면으로 이동 중',
        redirectDesc: '설정 페이지는 로그인 후에만 볼 수 있어 로그인 화면으로 이동합니다.',
      },
      account: {
        infoTitle: '계정 정보',
        emailLabel: '이메일',
        passwordChangeTitle: '비밀번호 변경',
        currentPassword: '현재 비밀번호',
        newPassword: '새 비밀번호',
        confirmPassword: '새 비밀번호 확인',
        submit: '변경',
        passwordChanged: '비밀번호가 변경되었습니다',
        socialLoginTitle: '소셜 로그인',
        connected: '연결됨',
        socialDesc: ' 계정으로 로그인하고 있습니다. 연결을 끊으려면 먼저 비밀번호를 설정하세요.',
        disconnected: '연결이 끊어졌습니다. 비밀번호로 로그인해주세요.',
        disconnect: '연결 끊기',
        disconnecting: '처리 중...',
        validation: {
          allFieldsRequired: '모든 필드를 입력해주세요',
          passwordMismatch: '새 비밀번호가 일치하지 않습니다',
          passwordMin: '비밀번호는 12자 이상이어야 합니다',
          changeFailed: '비밀번호 변경에 실패했습니다',
          disconnectFailed: '연결 끊기에 실패했습니다',
        },
      },
      security: {
        title: '2FA',
        enabled: '활성',
        disabled: '비활성',
        setupDesc: 'TOTP 앱(Google Authenticator 등)으로 2FA를 활성화합니다',
        enableButton: '2FA 활성화',
        setupGuide: 'QR 코드를 스캔한 후 인증 코드를 입력하세요',
        secretKey: '수동 키',
        codeLabel: '인증 코드',
        confirmButton: '확인',
        backupTitle: '백업 코드를 안전한 곳에 저장하세요',
        disableButton: '2FA 비활성화',
        disablePasswordLabel: '현재 비밀번호',
        disableCodeLabel: 'TOTP 코드',
        disableSubmit: '비활성화',
        cancelButton: '취소',
        error: {
          setupFailed: '2FA 설정 실패',
          confirmFailed: '코드 확인 실패',
          disableFailed: '비활성화 실패',
        },
      },
      audit: {
        desc: '세션 활동 및 접근 로그를 확인합니다',
        viewLog: '활동 로그 보기',
        recentTitle: '최근 활동 기록 (최대 20건)',
        viewAll: '전체 보기',
        empty: '활동 기록이 없습니다',
      },
      dataExport: {
        title: '내 데이터 내보내기',
        desc: '지금까지 piLoci가 정리해 둔 내 프로젝트와 기억을 한 묶음 zip 파일로 받습니다. 다른 서버로 옮기거나 백업해 둘 때 사용합니다.',
        export: '내보내기',
        exporting: '내보내는 중...',
        error: {
          generic: '내보내기에 실패했습니다',
          throttled: '잠시 후 다시 시도해주세요',
        },
      },
      dataImport: {
        title: '가져오기',
        desc: '다른 piLoci에서 내려받은 zip을 올려두면 현재 계정 안으로 조용히 합쳐집니다. 이름이 같은 프로젝트는 자동으로 새 이름으로 들여옵니다.',
        archiveLabel: '아카이브 (.zip)',
        reembedToggle: '임베딩 모델이 다르면 다시 계산해서 합치기',
        import: '가져오기',
        importing: '가져오는 중...',
        result: {
          projects: '프로젝트',
          renamed: '이름 변경',
          memories: '기억',
          unit: '개',
          reembedded: ' · 다시 임베딩됨',
        },
        error: {
          missingFile: '불러올 .zip 파일을 선택해주세요',
          embeddingMismatch: '내보낸 서버와 임베딩 모델이 다릅니다. 다시 임베딩을 켜고 시도해주세요.',
          tooLarge: '파일이 너무 큽니다. 더 작게 나눠 내보내주세요.',
          throttled: '잠시 후 다시 시도해주세요',
          generic: '가져오기에 실패했습니다',
        },
      },
      mcp: {
        title: 'MCP 설정',
        copy: '복사',
        copied: '복사됨',
      },
    },
    appShell: {
      locale: { trigger: '언어 선택', title: '언어를 선택하세요', desc: '인터페이스에 사용할 언어를 고르세요.' },
      nav: { dashboard: '대시보드', projects: '프로젝트', chat: '대화' },
      dropdown: { settings: '설정', activity: '활동 기록', admin: '관리자', logout: '로그아웃' },
      footer: { privacy: '개인정보 처리방침', terms: '서비스 약관' },
    },
    chat: {
      eyebrow: '메모리 채팅',
      title: '대화로 메모리 꺼내기',
      subtitle: '저장된 메모리에서 답을 가져옵니다. 인용 번호로 출처를 확인하세요.',
      projectSelectAria: '프로젝트 선택',
      projectPlaceholder: '프로젝트',
      noProjects: '아직 만든 프로젝트가 없습니다',
      pendingTitle: '세션 확인 중',
      pendingDesc: '대화를 준비하고 있습니다.',
      redirectTitle: '로그인 화면으로 이동 중',
      redirectDesc: '인증 상태를 확인했고, 로그인 페이지로 안전하게 전환하고 있습니다.',
      emptyTitle: '무엇을 찾고 있나요?',
      emptyDesc: '저장된 메모리만 보고 답합니다. 검색 가능한 자연어 질문이면 충분합니다.',
      examples: [
        '이번 주에 결정된 사항이 뭐였지?',
        'OAuth 관련해서 어떤 이슈가 있었어?',
        '내가 자주 쓰는 패턴 정리해줘',
      ],
      thinking: '메모리에서 단서를 찾는 중…',
      errorPrefix: '오류',
      placeholderDisabled: '프로젝트를 먼저 선택해 주세요',
      placeholderActive: '무엇이든 물어보세요',
      input: {
        questionAria: '질문 입력',
        sendAria: '보내기',
        stopAria: '중지',
        closeErrorAria: '닫기',
        micStartAria: '음성으로 질문하기',
        micStopAria: '음성 입력 중지',
        micRecordingTitle: '녹음 중… 클릭하면 멈춥니다',
        micIdleTitle: '마이크로 질문 입력 (한국어)',
      },
      dictation: {
        notAllowed: '마이크 권한이 거부되었습니다. 브라우저/시스템 마이크 권한을 허용한 뒤 다시 시도해 주세요.',
        audioCapture: '마이크를 찾을 수 없습니다. 입력 장치를 확인해 주세요.',
        network: '음성 인식 서비스에 연결할 수 없습니다. 네트워크 상태를 확인해 주세요.',
        noSpeech: '음성이 감지되지 않았습니다. 다시 시도해 주세요.',
        aborted: '음성 입력이 중지되었습니다.',
        insecureContext: 'HTTPS에서만 음성 입력을 사용할 수 있습니다.',
        unknown: '음성 인식 오류',
        consoleHint: '콘솔을 확인해 주세요.',
        startFailed: '음성 인식을 시작할 수 없습니다.',
        startRetry: '음성 인식을 시작할 수 없습니다. 잠시 후 다시 시도해 주세요.',
        silentFailure: '음성이 인식되지 않았습니다. 마이크 권한을 확인해 주세요.',
      },
    },
    device: {
      pendingTitle: '기기 승인 페이지 준비 중',
      pendingDesc: '인증 코드 처리 화면을 불러오고 있습니다.',
      readyDesc: '로그인 상태를 확인한 뒤 기기 승인 화면을 보여 드립니다.',
      cardTitle: '기기 승인',
      intro1: '터미널의 ',
      intro2: ' 출력에 표시된 8자리 코드를 입력하고 승인하면 해당 기기에 토큰이 자동 발급됩니다.',
      codeLabel: '인증 코드',
      approveButton: '이 기기 승인',
      approving: '승인 중…',
      denyButton: '거부',
      successMessage: '승인 완료. 이제 터미널로 돌아가시면 자동으로 진행됩니다.',
      deniedMessage: '요청을 거부했습니다. 새 코드로 다시 시도해 주세요.',
      footer1: ' 또는 ',
      footer2: ' 명령으로 발급된 코드입니다.',
      targets: {
        title: '설치 대상',
        hint: '체크한 클라이언트의 글로벌 설정에만 piloci MCP 서버를 머지합니다. 최소 한 개는 골라야 승인됩니다.',
        selectAll: '전체',
        clearAll: '해제',
        emptyError: '설치 대상을 한 개 이상 선택하세요.',
        list: [
          { kind: 'claude', label: 'Claude Code', path: '~/.claude/plugins/piloci/' },
          { kind: 'opencode', label: 'OpenCode', path: '~/.config/opencode/plugins/piloci.ts' },
          { kind: 'cursor', label: 'Cursor', path: '~/.cursor/mcp.json' },
          { kind: 'gemini', label: 'Gemini CLI', path: '~/.gemini/settings.json' },
          { kind: 'windsurf', label: 'Windsurf', path: '~/.codeium/windsurf/mcp_config.json' },
          { kind: 'codex', label: 'Codex CLI', path: '~/.codex/config.toml' },
          { kind: 'antigravity', label: 'AntiGravity', path: '~/.antigravity/mcp.json' },
          { kind: 'zed', label: 'Zed', path: '~/.config/zed/settings.json' },
        ],
      },
      error: {
        invalidFormat: '코드 형식은 ABCD-1234 입니다.',
        serverPrefix: '서버가',
        serverSuffix: '응답을 반환했습니다.',
        network: '네트워크 오류',
      },
    },
    authLayout: {
      heading1: '당신의 AI에게',
      heading2: '새로운 기억들을 추가해보세요',
      description: 'piLoci는 프로젝트별 격리된 메모리 공간으로 AI가 맥락을 잃지 않도록 돕습니다.',
      privacyLink: '개인정보 처리방침',
      termsLink: '서비스 약관',
    },
    authProviders: {
      kakao: '카카오로 계속하기',
      naver: '네이버로 계속하기',
      google: 'Google로 계속하기',
      github: 'GitHub로 계속하기',
    },
    dashboard: {
      eyebrow: '메모리 작업공간',
      title: '대시보드',
      subtitle: '최근 활동과 메모리 흐름을 한눈에 살펴봅니다.',
      newProject: '새 프로젝트',
      createTitle: '새 프로젝트 만들기',
      slugLabel: '슬러그 *',
      nameLabel: '이름 *',
      descLabel: '설명',
      descPlaceholder: '프로젝트 설명',
      cancel: '취소',
      creating: '생성 중...',
      create: '생성',
      validation: {
        slugAndNameRequired: '슬러그와 이름을 모두 입력해주세요',
        createFailed: '프로젝트 생성에 실패했습니다',
      },
      stats: { projects: '프로젝트', totalMemories: '총 메모리', totalKnacks: '총 패턴', status: '상태', syncing: '동기화 중', ready: '준비' },
      summary: {
        activityTitle: '최근 활동',
        activityEmpty: '아직 들어온 세션이 없습니다',
        recentMemoriesTitle: '최근 메모리',
        recentMemoriesEmpty: '아직 메모리가 없습니다',
        topKnacksTitle: '자주 보이는 패턴',
        topKnacksEmpty: '아직 패턴이 없습니다',
        recentSessionsTitle: '최근 세션',
        recentSessionsEmpty: '아직 세션이 없습니다',
        topTagsTitle: '자주 쓰는 태그',
        topTagsEmpty: '태그 없음',
        viewAll: '전체 보기',
        viewProject: '프로젝트로 이동',
        sessionMemories: '메모리 {count}',
        sessionPending: '분석 중',
        cols: {
          memory: '메모리',
          project: '프로젝트',
          tags: '태그',
          when: '조건',
          then: '대응',
          domain: '도메인',
          count: '횟수',
          tag: '태그',
          status: '상태',
          time: '시각',
        },
      },
      empty: { title: '아직 프로젝트가 없습니다', create: '프로젝트 만들기' },
      error: { title: '프로젝트를 불러오지 못했습니다', retry: '재시도' },
      pending: { title: '세션 확인 중', desc: '대시보드에 필요한 계정 정보를 불러오고 있습니다.' },
      redirect: { title: '로그인 화면으로 이동 중', desc: '인증 상태를 확인했고, 로그인 페이지로 안전하게 전환하고 있습니다.' },
    },
    projects: {
      eyebrow: '프로젝트 메모리',
      breadcrumb: '대시보드',
      notes: '노트',
      nodes: '노드',
      edges: '관계',
      tags: '태그',
      knacks: '패턴',
      sessions: '세션',
      memories: '메모리',
      lastActive: '마지막 기록',
      lastAnalyzed: '마지막 정리',
      neverActive: '기록 없음',
      cardMemories: '메모리',
      cardKnacks: '패턴',
      tabMemories: '메모리',
      tabKnacks: '패턴',
      tabSessions: '원본 세션',
      knackDomain: '도메인',
      knackConfidence: '신뢰도',
      knackCount: '관찰',
      knackEvidence: '근거',
      knacksEmpty: '아직 추출된 패턴이 없습니다',
      sessionMeta: '{kb} KB · {client}',
      sessionStatusProcessed: '메모리 {count}건 추출',
      sessionStatusPending: '분석 대기',
      sessionStatusFailed: '분석 실패',
      sessionsEmpty: '아직 들어온 세션이 없습니다',
      viewTranscript: '원본 보기',
      hideTranscript: '접기',
      transcriptLoading: '불러오는 중...',
      transcriptFailed: '불러오지 못했습니다',
      openButton: '열기',
      editAria: '프로젝트 편집',
      deleteAria: '프로젝트 삭제',
      editTitle: '프로젝트 편집',
      editSlugLabel: '슬러그',
      editSlugHelp: '슬러그는 메모리·토큰 매핑 키라 변경할 수 없습니다.',
      editNameLabel: '이름 *',
      editDescLabel: '설명',
      editDescPlaceholder: '프로젝트 설명',
      editCancel: '취소',
      editSaving: '저장 중...',
      editSave: '저장',
      editNameRequired: '이름은 비워둘 수 없습니다',
      editSaveFailed: '저장에 실패했습니다',
      deleteTitle: '삭제',
      deleteDesc: '이 프로젝트와 연결된 모든 메모리·노트가 함께 사라집니다. 되돌릴 수 없습니다.',
      deleteConfirm: '삭제',
      noNotes: '노트가 없습니다',
      quickSelect: '빠른 선택',
      quickSelectDesc: '번호를 누르면 해당 노트로 바로 이동합니다.',
      mcpConfig: 'MCP 설정',
      pending: { title: '프로젝트 위치 확인 중', desc: '열어야 할 프로젝트를 찾는 중이며, 정보가 없으면 대시보드로 돌아갑니다.' },
    },
    audit: {
      eyebrow: '보안 타임라인',
      title: '활동 기록',
      subtitle: '보안 이벤트 및 접근 기록',
      filter: '필터',
      // Keys MUST match the action string written to audit_logs.action by the
      // backend (see piloci.auth.local + piloci.api.routes._admin_audit).
      actions: {
        all: '전체',
        signup: '회원가입',
        login_success: '로그인 성공',
        login_fail: '로그인 실패',
        login_fail_totp: '2FA 인증 실패',
        password_reset: '비밀번호 재설정',
        token_created: '토큰 생성',
        token_revoked: '토큰 폐기',
        project_created: '프로젝트 생성',
        project_deleted: '프로젝트 삭제',
        admin_toggle_admin: '관리자 권한 변경',
        admin_toggle_active: '계정 활성/비활성',
        admin_delete_user: '사용자 삭제',
      },
      table: { time: '시간', event: '이벤트', ip: 'IP', userAgent: 'User Agent' },
      empty: { error: '활동 기록을 불러오지 못했습니다', noLogs: '기록된 이벤트가 없습니다' },
      pagination: { prev: '이전', next: '다음', page: '페이지' },
      pending: { title: '활동 기록 준비 중', desc: '로그인 상태와 필터 설정을 복원한 뒤 활동 기록을 표시합니다.' },
      redirect: { title: '로그인 화면으로 이동 중', desc: '활동 기록은 보호된 화면이라 로그인 페이지로 이동합니다.' },
    },
    tokenManager: {
      desc: 'API 토큰으로 외부 클라이언트에서 piLoci에 접근합니다',
      issue: '발급',
      issuing: '발급 중...',
      tokenCreated: '토큰 발급 완료',
      tabs: { token: '토큰', mcpServer: 'MCP 서버', install: 'Claude 설치', claudeMd: 'CLAUDE.md' },
      tokenWarning: '이 토큰은 다시 볼 수 없습니다. 지금 복사하세요.',
      mcpInstructions: '에 아래 내용을 붙여넣으세요. 기존 파일이 있으면 mcpServers 키만 병합합니다.',
      mcpNote: '설정 후 Claude Code를 재시작하면 memory, recall, recommend 툴이 자동으로 활성화됩니다.',
      quickInstallTitle: '한 줄 설치 (uvx)',
      quickInstallDesc: '아래 명령어 한 줄로 hook.py · config.json · ~/.claude/settings.json 까지 자동 머지됩니다. install code는 한 번만, 10분 뒤 만료.',
      quickStep1: '① 명령어 복사',
      quickStep1Desc: '아래 박스 우측의 복사 버튼을 누르세요. (이 명령은 토큰이 한 번 박혀 있는 일회성 install code입니다)',
      quickStep2: '② 터미널에 붙여넣고 실행',
      quickStep2Desc: 'uvx 가 설치돼 있어야 합니다 (없으면 `pip install uv`). 실행되면 ~/.config/piloci 와 ~/.claude/settings.json 을 알아서 손봅니다.',
      quickStep3: '③ Claude Code 재시작',
      quickStep3Desc: '재시작하면 memory / recall / recommend MCP 툴이 자동으로 활성화됩니다.',
      quickInstallNoCode: '이 토큰에는 install code가 발급되지 않았습니다. 새 토큰을 발급하면 자동 설치 명령이 나옵니다.',
      manualInstallToggle: '수동 설치 보기',
      manualInstallHide: '수동 설치 접기',
      manualInstallNote: '자동 설치를 쓸 수 없는 환경(스크립트 차단, 별도 머신 등)에서만 사용하세요.',
      hookStep1: '① 스크립트 다운로드 (한 번만)',
      hookStep1Desc: '한 번 설치하면 토큰이 바뀌어도 재설치 불필요.',
      hookStep2: '② config.json 저장',
      hookStep2Desc: '다음 내용을 ~/.config/piloci/config.json 에 저장하세요. 토큰 교체 시 이 파일만 업데이트.',
      hookStep3: '③ settings.json 설정',
      hookStep3Desc: '~/.claude/settings.json 의 hooks 키에 병합하세요.',
      claudeMdInstructions: '프로젝트 루트의 CLAUDE.md에 붙여넣으세요. Claude가 세션 시작에 자동으로 이전 기억을 불러오고, 대화 중 중요한 내용을 memory 도구로 저장합니다.',
      formName: '토큰 이름',
      formNamePlaceholder: '예: Claude Code',
      formScope: '범위',
      scopeUser: '사용자 전체',
      scopeProject: '프로젝트 (MCP + SessionStart 훅 설정 자동 생성)',
      formProject: '프로젝트',
      selectProject: '선택',
      noTokens: '발급된 토큰이 없습니다',
      formExpire: '유효기간',
      expireOptions: {
        d30: '30일',
        d90: '90일',
        d180: '6개월',
        d365: '1년',
        none: '만료 없음',
      },
      tableHeaders: { name: '이름', scope: '범위', issued: '발급일', lastUsed: '마지막 사용', expires: '만료일' },
      expiresNone: '만료 없음',
      expired: '만료됨',
      confirmRevoke: ' 토큰을 폐기하시겠습니까?',
      cancel: '취소',
      mcpConfigFor: 'MCP 설정 —',
      envHint: '환경 변수로 토큰을 관리할 때 사용하세요.',
      notInstalled: '미설치',
      installedOn: '설치',
      loadFailed: '토큰 목록을 불러오지 못했습니다',
      retry: '다시 시도',
      mcpClaudeHint: 'Claude Desktop / Claude Code / Cursor — .mcp.json 또는 claude_desktop_config.json',
      mcpClaudeOr: '또는',
      mcpOpencodeHint: 'OpenCode — opencode.json',
      mcpOpencodeRemote: '사용',
      crossPlatformLabel: 'Windows / 크로스플랫폼 (uvx)',
      tokenPlaceholder: '<여기에_토큰_붙여넣기>',
      tokenPasteNotice: '토큰은 발급 시에만 확인할 수 있습니다. 아래 설정에서 <여기에_토큰_붙여넣기> 부분을 발급받은 토큰으로 교체하세요.',
    },
    llm: {
      heading: '외부 LLM 백업',
      description: '로컬 Gemma가 막히면 우선순위 순으로 외부 OpenAI-compatible 모델로 폴백합니다.',
      add: '추가',
      addTitle: '외부 LLM 추가',
      editTitle: '외부 LLM 편집',
      deleteConfirmDesc: '이 외부 LLM 백업을 목록에서 제거합니다. API 키도 함께 삭제됩니다.',
      removeButton: '제거',
      empty: '등록된 외부 LLM이 없습니다. Gemma만 사용 중.',
      loadFailed: '목록을 불러오지 못했습니다.',
      enabled: '활성',
      disabled: '비활성',
      priorityLabel: '우선순위 {priority}',
      modelLabel: '모델',
      keyLabel: '키',
      ariaToggleOn: '활성화',
      ariaToggleOff: '비활성화',
      ariaEdit: '편집',
      ariaDelete: '삭제',
      form: {
        nameLabel: '이름 *',
        baseUrlLabel: 'Base URL *',
        baseUrlHelp: 'OpenAI-compatible 엔드포인트의 베이스. /v1/chat/completions는 자동 보정됨.',
        modelLabel: '모델 *',
        apiKeyLabel: 'API 키',
        apiKeyEditNote: '비워두면 기존 키 유지',
        priorityLabel: '우선순위',
        priorityHelp: '낮을수록 먼저 시도',
        enabledLabel: '활성화',
        cancel: '취소',
        saving: '저장 중...',
        save: '저장',
        addAction: '추가',
        allFieldsRequired: '이름·Base URL·모델·API 키 모두 필요합니다',
        addFailed: '추가에 실패했습니다',
        saveFailed: '저장에 실패했습니다',
      },
    },
    vaultNote: {
      tags: '태그',
      noPreview: '미리보기가 없습니다',
      selectNote: '노트를 선택하세요',
      linkedNotes: '연결된 노트',
    },
    projectCard: {
      workspace: '프로젝트 워크스페이스',
      memories: '메모리',
      open: '열기',
    },
    themeToggle: { toLightAriaLabel: '라이트 모드로 전환', toDarkAriaLabel: '다크 모드로 전환' },
};

type CopyShape = typeof ko;

const en: CopyShape = {
    metadata: { description: 'High-performance MCP memory engine for Raspberry Pi', title: 'piLoci, The Second Brain That Helps AI Remember' },
    common: { brandName: 'piLoci', login: 'Log in', signup: 'Get Started', badge: 'Self-Hosted', copy: 'Copy', copied: '✓ Copied', cancel: 'Cancel', confirm: 'Confirm', processing: 'Processing...', loading: 'Loading...', backToHome: 'Home' },
    landing: {
      quotes: [
        '"Memory is the mother of all wisdom" — Aeschylus',
        '"Memory is the treasure house of the mind"',
        '"What is forgotten does not exist" — Goethe',
        '"We exist only as much as we remember" — Pascal',
        '"Memory is the treasurer of the mind" — Thomas Fuller',
        '"Only those who remember the past can open the future"',
        '"Without memory, experience is impossible" — Kant',
        '"The greatest possession is memory" — Chiron',
        '"Memory is the shadow of the soul" — Homer',
        '"Memory creates more than oblivion ever could" — Benjamin Franklin',
        '"Our memory is our identity" — John Locke',
        '"Memory is the guardian of time" — Erasmus',
        '"Not forgetting is itself a form of learning"',
        '"Memory is the mother and keeper of all things" — Augustine',
        '"A good memory is part of wisdom" — Seneca',
        '"A mind without memory is a house without a dweller"',
        '"Those who cannot remember the past are condemned to repeat it" — Santayana',
        '"Memory is the storehouse of experience and fountain of wisdom"',
        '"The most vivid memories leave the deepest marks"',
        '"Oblivion is mercy; memory is blessing"',
        '"Memory is the treasury and guardian of all things" — Cicero',
        '"Everything begins with memory"',
        '"Experience lives on under the name of memory"',
        '"One who remembers is never truly alone"',
        '"Memory is the root of existence" — Marcel Proust',
        '"Strong memory makes a strong life"',
        '"Remembering the past is the path to understanding the present"',
        '"Memory is the most enduring evidence of love"',
        '"Learning is simply another name for memory" — Plato',
        '"Memory is the only thing that lives and breathes forever"',
        '"Memory is the key to reclaiming lost time" — Proust',
        '"Memory is the core of identity"',
        '"True memory is engraved in the heart"',
        '"Memory tells us who we really are"',
        '"Wisdom is the crystallization of memory"',
        '"Memory is the continuity of existence" — David Hume',
        '"Memory is the mirror of the mind" — Tolstoy',
        '"Those who live in memory never die"',
        '"Memory is the most faithful friend" — Henry Ward Beecher',
        '"Memory is the bridge between past and present"',
        '"The most precious things are never forgotten"',
        '"Memory is the alchemy that turns experience into wisdom"',
        '"Memory is the inner library of us all" — Montaigne',
        '"A good memory is evidence of a good mind" — Aristotle',
        '"Memory is the trigger of life" — Nietzsche',
        '"Where there is memory, there is hope"',
        '"Memory is the mother of experience" — Leonardo da Vinci',
        '"Remember the past — it is the foundation of the future" — Cicero',
        '"Memory is the most eternal possession we own"',
        '"Oblivion is death, memory is resurrection" — Baudelaire',
      ],
      titleLines: ['KNOWLEDGE MEMORY', 'FOR YOUR AI CORE'],
      descriptionLines: [
        'piLoci is a self-hosted MCP memory server built to save tokens, I/O, and LLM calls on low-power devices like Raspberry Pi.',
      ],
      terminal: {
        title: 'piLoci MCP',
        examples: [
          {
            q: 'What was I working on yesterday?',
            tool: 'recall',
            toolArgs: '{"query": "yesterday project", "limit": 3}',
            result: '3 previews — [piloci/scaffolding] [piloci/MCP routing] [piloci/auth]',
            a: 'You were working on piLoci — refactored MCP routing to /mcp prefix, mounted SSE transport as a Starlette sub-app.',
          },
          {
            q: 'Where did I leave off? Catch me up',
            tool: 'recall',
            toolArgs: '{"query": "current progress status", "limit": 5}',
            result: '5 previews — only the relevant memories from a much larger project history',
            a: 'Landing page UI in progress — dark theme violet tones applied, MCP routing refactored to /mcp. Next: Docker production setup.',
          },
          {
            q: 'Remind me of the auth approach we decided on',
            tool: 'recall',
            toolArgs: '{"query": "auth authentication token session", "limit": 3}',
            result: '3 previews — [auth routes] [2FA setup] [token scopes]',
            a: 'Dual auth: JWT sessions + TOTP 2FA, argon2id password hashing, scoped API tokens per project. Refresh tokens in httpOnly cookies.',
          },
          {
            q: 'What was that book I was reading?',
            tool: 'recall',
            toolArgs: '{"query": "book reading list recommendation", "limit": 5}',
            result: '5 previews — [reading notes] [recommendations] [finished] [library] [book club]',
            a: 'You were halfway through "Sapiens" — chapter 7. Up next: "Thinking, Fast and Slow". Also "The Art of Strategy" from last month\'s recommendation.',
          },
          {
            q: 'What do I need to prep for next week\'s meeting?',
            tool: 'recall',
            toolArgs: '{"query": "meeting prep agenda", "limit": 3}',
            result: '3 previews — [weekly standup] [sprint review] [backlog]',
            a: 'Tuesday sprint review: demo the landing page, present Docker deployment progress. Thursday backlog grooming to prioritize v0.3 milestones.',
          },
          {
            q: 'Do you remember how I like my coffee?',
            tool: 'recall',
            toolArgs: '{"query": "coffee preference taste", "limit": 3}',
            result: '3 previews — [taste profile] [cafe notes] [gift list]',
            a: 'Light roast fan — Ethiopia Yirgacheffe is your go-to. Blue Bottle single origin regular. Black, no sugar, no syrup. Definitely not a pumpkin spice person.',
          },
          {
            q: 'Remind me what to grab from the store',
            tool: 'recall',
            toolArgs: '{"query": "grocery shopping list todo", "limit": 5}',
            result: '5 previews — [shopping list] [recipes] [meal plan] [fridge inventory] [deals]',
            a: 'Running low on milk, eggs, cherry tomatoes, and avocados. That pasta recipe you saved needs olive oil too. Don\'t forget the fish from the fishmonger.',
          },
          {
            q: 'Gather the constraints for this project',
            tool: 'recall',
            toolArgs: '{"query": "constraints security requirements", "limit": 5}',
            result: '5 previews — [CLAUDE.md] [routes.py] [sse.py] [.env.example] [security]',
            a: 'Collected: ① argon2id only (no bcrypt) ② ORM only, no raw SQL ③ JWT secret via env vars ④ (user_id, project_id) filter required ⑤ orjson mandatory',
          },
          {
            q: 'When\'s my uncle\'s birthday? What did I get him?',
            tool: 'recall',
            toolArgs: '{"query": "uncle birthday gift family", "limit": 3}',
            result: '3 previews — [family dates] [gift records] [calendar]',
            a: 'Uncle\'s birthday is May 12th. Last year you got him a Montblanc fountain pen. Nothing picked out yet for this year. He mentioned health issues in March.',
          },
          {
            q: 'Show me the itinerary from my last trip',
            tool: 'recall',
            toolArgs: '{"query": "travel itinerary Fukuoka trip", "limit": 5}',
            result: '5 previews — [itinerary] [restaurants] [hotel] [flights] [expenses]',
            a: 'Fukuoka 4 days: Day 1 Tenjin & yatai, Day 2 Dazaifu & Unzen onsen, Day 3 Hakata Kushida & Canal City. Hotel was 5 min walk from Hakata Station.',
          },
          {
            q: 'Docker build keeps failing, can you check the logs?',
            tool: 'recall',
            toolArgs: '{"query": "Docker build error failure log", "limit": 3}',
            result: '3 previews — [Dockerfile fix] [CI logs] [arm64 issue]',
            a: 'Same issue last time — multi-arch build had a corrupted pip cache layer for arm64. Rebuilding with --no-cache fixed it.',
            followUp: {
              q: 'Apply the Dockerfile fix from last time',
              tool: 'memory',
              toolArgs: '{"action": "save", "content": "Dockerfile arm64 cache fix applied", "tags": ["docker", "fix", "arm64"]}',
              result: 'Saved — Dockerfile arm64 build fix',
              a: 'Applied the cache-related fix to the Dockerfile. Want me to rebuild?',
            },
          },
        ],
      },
      stats: {
        latency: '2ms',
        reduction: '80%+',
        uptime: '100%',
        latencyLabel: 'Vector Search',
        reductionLabel: 'Token Savings',
        uptimeLabel: 'Local Operation',
      },
      sections: {
        intro: {
          title: 'Introduction',
          content: 'piLoci is a self-hosted MCP memory server designed for low-power environments like Raspberry Pi — saving tokens, I/O, and LLM calls.',
        },
        features: {
          title: 'A quiet analyst behind you, reading context so you don\'t have to',
          subtitle: [
            'Conversation stays natural while the backend quietly decides which context deserves long-term memory.',
            'Embeddings are reused through LRU cache and batched ingest, while search returns excerpts first and loads full text only when needed.',
            'Vault JSON stays cached on disk, so graph and export views open like a well-kept notebook instead of a fresh rebuild.',
          ],
          list: [
            { title: 'Context Isolation', desc: 'Per-project memory separation. No context mixing.' },
            { title: 'AST-based Extraction', desc: 'Precise code structure preservation via Tree-sitter.' },
            { title: '2ms Vector Search', desc: 'Semantic search under 2ms, even on Pi 5.' },
            { title: '100% Local', desc: 'No cloud dependency. Zero data leaks.' },
            { title: 'Auto Curation', desc: 'Extracts and stores key info from conversations.' },
            { title: 'Batch Embedding Ingest', desc: 'Embed one ingest job in a single batch to cut executor hops on Pi-class hardware.' },
            { title: 'Preview-first Recall', desc: 'Excerpts first, full text only when needed.' },
            { title: 'Vault Workspace', desc: 'Reuse cached notes, graph, and tags without rebuilding every read.' },
            { title: 'Telegram Summaries', desc: 'Only meaningful sessions get summarized.' },
            { title: 'Obsidian Export', desc: 'Download the cached vault as a zip archive.' },
            { title: 'MCP Standard', desc: 'Connect with Claude, Cursor, Windsurf, and more.' },
          ]
        },
        quickStart: {
          title: 'Quick Start',
          installTitle: '1. Installation via uvx',
          installDesc: 'Run the server immediately with the following command without complex setup.',
          setupTitle: '2. Backend Config (.env)',
          setupDesc: 'Freely configure SQLite paths and indexing engines via environment variables.',
        },
        install: {
          uvEyebrow: 'Prerequisite — uv',
          eyebrow: 'Install',
          uninstallEyebrow: 'Remove',
          recommendedLabel: 'Recommended',
          setup: { title: 'uvx oc-piloci setup', desc: '' },
          install: { title: 'uvx oc-piloci install', desc: '' },
          uninstall: { label: 'Copy', cmd: 'uvx oc-piloci uninstall --yes' },
          platformsLabel: 'Supported clients',
          platformsHint: '',
          platforms: [
            { name: 'Claude Code', status: 'auto' },
            { name: 'OpenCode', status: 'auto' },
            { name: 'Cursor', status: 'auto' },
            { name: 'Gemini CLI', status: 'auto' },
            { name: 'Windsurf', status: 'auto' },
            { name: 'Codex CLI', status: 'auto' },
            { name: 'AntiGravity', status: 'auto' },
            { name: 'Zed', status: 'auto' },
            { name: 'ChatGPT Desktop', status: 'manual' },
          ],
          statusLabels: { auto: 'Auto', manual: 'Manual' },
        },
        capabilities: {
          title: 'Only What You Need — Radical Minimalism',
          desc: 'Minimal tool count by design — to preserve LLM prompt context while maximizing efficiency.',
          note: 'Minimal tool count by design — to preserve LLM prompt context while maximizing efficiency.',
          list: [
            { name: 'memory', desc: 'Save new facts or project context to memory, or remove outdated entries by ID.' },
            { name: 'recall', desc: 'Preview matches first, then selectively fetch full content or export large results to markdown.' },
            { name: 'listProjects', desc: 'Fetch the 5-minute cached project list quickly, or force a refresh when needed.' },
          ]
        },
        curation: {
          title: 'A silent analyst organizing the context you leave behind',
          eyebrow: 'Silent Analyst',
          paragraphs: [
            'piLoci is not a notebook waiting for manual save clicks. It quietly takes notes on important context while people work and talk.',
            'The analyst picks out decisions and constraints worth keeping, merges overlapping points, and organizes project context into notes and tags.',
          ],
          stages: [
            { label: 'Raw session', desc: 'Preserve the working trail.' },
            { label: 'Auto curation', desc: 'Promote what should last.' },
            { label: 'Memory graph', desc: 'Reveal connected knowledge.' },
          ],
          graphTitle: 'Auto-Generated Memory Graph',
          graphDesc: 'Decisions, constraints, preferences, and work traces become a constellation of project memory.',
          graphNodes: {
            project: { label: 'Project', value: 'piLoci' },
            decision: { label: 'Decision', value: 'local first' },
            curated: { label: 'Curated Memory', value: 'quiet context' },
            constraint: { label: 'Constraint', value: 'Pi 5 budget' },
            preference: { label: 'Preference', value: 'no cloud leak' },
          },
        },
        pricing: {
          title: 'Transparent Open Source, Total Freedom',
          desc: [
            'piLoci is fully open source — every line of code is public.',
            'Anyone can contribute and improve it together.',
          ],
          features: [
            'Unlimited Projects',
            'Local SQLite + LanceDB',
            'Commercial Use (MIT)',
            'Zero Telemetry',
            'Obsidian-compatible Workspace',
            'Multi-user Team Support',
            'Full Self-hosted (Docker)',
            'Google OAuth + TOTP 2FA',
          ],
          engineering: {
            title: 'Put Your Idle Raspberry Pi to Work!',
            desc: 'Every architectural decision was made with "zero cost, minimal resources" in mind.',
            items: [
              { label: 'LanceDB', desc: 'No cloud vector DB needed. Local file-based embedding storage.' },
              { label: 'SQLite', desc: 'No external RDBMS. All metadata handled locally.' },
              { label: 'fastembed (ONNX)', desc: 'CPU-only 384-dim embeddings. No GPU or torch required.' },
              { label: 'LRU Embedding Cache', desc: 'Skips re-computation for repeated texts. Instant on cache hit.' },
              { label: 'Batch embed ingest', desc: 'The curator worker embeds extracted memories in one shot to reduce calls on low-power CPUs.' },
              { label: 'Preview-first recall', desc: 'Avoids dumping large search payloads into the model context unless explicitly requested.' },
              { label: 'Telegram session summary', desc: 'Backend-only session alerts for meaningful work with zero additional LLM token cost.' },
              { label: 'Cached vault export', desc: 'Persist vault.json on disk and generate an Obsidian-style zip on demand.' },
            ],
          },
        }
      },
      footer: '© piLoci 2026. Husband of Rebekah.',
      pending: { title: 'Loading piLoci', desc: 'Checking session and screen state before redirecting.' },
    },
    privacy: {
      title: 'Privacy Policy',
      subtitle: 'piLoci Privacy Policy',
      preamble: 'We comply with personal data protection regulations and relevant guidelines.',
      sections: [
        {
          title: '1. Information We Collect',
          content: 'We collect information to provide smooth service and communication.',
          items: ['Required: Email address', 'Automatically collected: Activity logs, cookies, etc.', 'Activity logs include login times, API call records, and project creation/modification history.'],
        },
        {
          title: '2. Data Retention',
          content: '',
          items: ['Account information is deleted immediately upon account deletion.', 'Project data and memories are retained until the user deletes them.', 'Audit logs are kept while the account is active.'],
        },
        {
          title: '3. Purpose of Data Collection',
          content: '',
          items: [
            'Email: User verification, duplicate registration prevention, fraud prevention',
            'Password: Stored using Argon2id one-way hash encryption. The plaintext is never collected.',
            'Activity and access logs: Fraud prevention, unauthorized use prevention, service improvement',
          ],
        },
        {
          title: '4. Third-Party Sharing',
          content: '',
          items: ['piLoci follows a Local-first philosophy — all data is stored only on your device.', 'No personal information is transmitted to external servers or third parties.', 'Data is transmitted only when the user explicitly opts into cloud synchronization.'],
        },
        {
          title: '5. Data Destruction',
          content: '',
          items: ['All personal information is destroyed immediately upon account deletion.', 'Passwords are stored only as hashes and cannot be recovered.', 'All user data is permanently deleted upon service termination.'],
        },
        {
          title: '6. Technical and Administrative Safeguards',
          content: '',
          items: ['Passwords: Argon2id one-way hash encryption', 'Authentication: JWT-based session management', 'API access: Project-scoped isolated tokens', 'Network: HTTPS/TLS encrypted communication', 'Database: User and project-level access control'],
        },
        {
          title: '7. Your Rights',
          content: '',
          items: ['You may view, modify, or delete your personal information at any time.', 'Manage directly from the Settings page within the service.', 'For privacy-related inquiries, contact us via email for immediate handling.'],
        },
      ],
      dates: 'Published: January 1, 2026 / Effective: January 1, 2026',
    },
    terms: {
      title: 'Terms of Service',
      subtitle: 'piLoci Terms of Service',
      preamble: 'These terms govern the conditions and procedures for using piLoci, and define the rights, obligations, and responsibilities of users and operators.',
      sections: [
        {
          title: '1. Application of Terms',
          content: '',
          items: [
            'These terms apply to all users of the piLoci service.',
            'The operator may modify these terms and will notify users of changes via in-service announcements.',
            'If you do not agree to the modified terms, you may discontinue use of the service.',
          ],
        },
        {
          title: '2. Service Description',
          content: '',
          items: [
            'piLoci is a self-hosted memory service that stores, searches, and manages AI conversation context on a per-project basis.',
            'Core features: conversation distillation (automatic key extraction), semantic search, project-isolated memory, MCP tool interface.',
            'Service content may change for improvement, with advance notice for significant changes.',
          ],
        },
        {
          title: '3. User Responsibilities',
          content: '',
          items: [
            'You must not use another person\'s account without authorization.',
            'Exploiting security vulnerabilities or causing system overload is prohibited.',
            'You bear full responsibility for the content stored in conversations.',
          ],
        },
        {
          title: '4. Data Ownership',
          content: '',
          items: [
            'All data you input and generate remains your property.',
            'The operator does not access or utilize your data without consent.',
            'In a local-first architecture, data is stored on your device.',
          ],
        },
        {
          title: '5. Service Suspension and Termination',
          content: '',
          items: [
            'The operator may temporarily suspend the service for maintenance.',
            'Service termination will be announced at least 30 days in advance, with an opportunity to export your data.',
            'You may delete your account and destroy all data at any time.',
          ],
        },
        {
          title: '6. Limitation of Liability',
          content: '',
          items: [
            'As a self-hosted service, system operation and data backup responsibilities lie with the deployer.',
            'We do not guarantee the accuracy of AI-generated distillation results.',
            'We are not liable for service interruptions due to force majeure events.',
          ],
        },
      ],
      dates: 'Published: January 1, 2026 / Effective: January 1, 2026',
    },
    admin: {
      eyebrow: 'Admin console',
      title: 'User Management',
      description: 'Manage user accounts.',
      filterAll: 'All',
      filterPending: 'Pending',
      filterApproved: 'Approved',
      filterRejected: 'Rejected',
      filterInactive: 'Inactive',
      emptyMessage: 'No users with this status.',
      approve: 'Approve',
      reject: 'Reject',
      rejectReasonLabel: 'Rejection reason',
      rejectReasonPlaceholder: 'Enter rejection reason',
      rejectConfirm: 'Confirm rejection',
      cancel: 'Cancel',
      status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected' },
      reviewedAt: 'Reviewed',
      noReviewer: '—',
      oauthProvider: 'Social',
      createdAt: 'Joined',
      lastLogin: 'Last login',
      neverLoggedIn: 'Never logged in',
      confirmReject: 'Reject this user\'s signup request?',
      emailLabel: 'Email',
      statusLabel: 'Status',
      actionLabel: 'Action',
      loadError: 'Failed to load user list',
      retry: 'Retry',
      emptyPending: 'No pending signup requests',
      promoteAdmin: 'Promote to Admin',
      demoteAdmin: 'Demote from Admin',
      activateUser: 'Activate Account',
      deactivateUser: 'Deactivate Account',
      deleteUser: 'Delete Account',
      deleteConfirmTitle: 'Delete Account',
      deleteConfirmMessage: 'Delete this user and all their data? This cannot be undone.',
      deleteConfirm: 'Delete',
      // Toast messages — caller replaces {email} at use site.
      toastApproved: '{email} approved',
      toastRejected: '{email} rejected',
      toastDeleted: '{email} deleted',
      toastPromoted: '{email} promoted to admin',
      toastDemoted: '{email} demoted from admin',
      toastActivated: '{email} activated',
      toastDeactivated: '{email} deactivated',
      twoFactor: '2FA',
      enabled: 'On',
      disabled: 'Off',
      adminBadge: 'Admin',
      inactiveBadge: 'Inactive',
      searchPlaceholder: 'Search by email or name...',
      confirmPromote: 'Promote this user to admin?',
      confirmDemote: 'Remove admin privileges from this user?',
      confirmDeactivate: 'Deactivate this account?',
      confirmActivate: 'Activate this account?',
      you: '(You)',
      statsTotal: 'Total',
      statsPending: 'Pending',
      statsAdmins: 'Admins',
    },
    signup: {
      approvalTitle: 'Signup Complete',
      approvalMessage: 'Your account is pending admin approval.',
      approvalSubmessage: 'You can log in once approved.',
      goToLogin: 'Go to login',
      title: 'Sign Up',
      subtitle: 'Create your piLoci account',
      nameLabel: 'Name',
      namePlaceholder: 'John Doe',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      passwordHint: '12+ chars, uppercase + lowercase + digit',
      confirmPasswordLabel: 'Confirm password',
      submitting: 'Signing up...',
      submit: 'Sign Up',
      or: 'or',
      hasAccount: 'Already have an account?',
      loginLink: 'Log in',
      validation: {
        nameMin: 'Name must be at least 2 characters',
        emailInvalid: 'Enter a valid email address',
        passwordMin: 'Password must be at least 12 characters',
        passwordUpper: 'Must include an uppercase letter',
        passwordLower: 'Must include a lowercase letter',
        passwordDigit: 'Must include a digit',
        confirmRequired: 'Enter password confirmation',
        confirmMismatch: 'Passwords do not match',
      },
      error: {
        emailDuplicate: 'Email address already in use',
        generic: 'An error occurred during signup',
      },
    },
    login: {
      approvalPending: 'Your account is pending admin approval. Please wait for approval before logging in.',
      approvalRejected: 'Your signup request has been rejected. Please contact the administrator.',
      approvalPendingShort: 'Account pending admin approval',
      approvalRejectedShort: 'Signup request was rejected',
      title: 'Log In',
      subtitle: 'Access your project workspace',
      emailLabel: 'Email',
      passwordLabel: 'Password',
      submitting: 'Authenticating...',
      submit: 'Log In',
      or: 'or',
      forgotPassword: 'Forgot your password?',
      noAccount: "Don't have an account?",
      signupLink: 'Sign Up',
      resetNotice: 'Your password has been changed. Please log in with your new password.',
      validation: {
        emailInvalid: 'Enter a valid email address',
        passwordRequired: 'Enter your password',
      },
      error: {
        locked: 'Account is locked',
        invalidCredentials: 'Invalid email or password',
        oauthCancelled: 'Social login was cancelled. Please try again.',
        oauthExpired: 'Login request expired or invalid. Please try again.',
        oauthFailed: 'An error occurred during social login. Please try again.',
      },
    },
    forgotPassword: {
      title: 'Forgot Password',
      subtitle: 'Enter the email you signed up with',
      subtitle2: "and we'll send you a reset token",
      emailLabel: 'Email',
      sentMessage: 'A reset token has been issued.',
      sentMessage2: 'Use the button below to change your password.',
      resetLink: 'Reset Password',
      submitting: 'Sending...',
      submit: 'Get Reset Token',
      backToLogin: 'Back to login',
      validation: {
        emailInvalid: 'Enter a valid email address',
      },
      error: {
        generic: 'An error occurred during the request',
      },
    },
    resetPassword: {
      title: 'Reset Password',
      subtitle: 'Enter your new password',
      tokenLabel: 'Reset token',
      tokenPlaceholder: 'Paste your token here',
      newPasswordLabel: 'New password',
      confirmPasswordLabel: 'Confirm password',
      passwordHint: '12+ chars, uppercase + lowercase + digit',
      submitting: 'Changing...',
      submit: 'Change Password',
      backToLogin: 'Back to login',
      loading: 'Loading...',
      validation: {
        tokenRequired: 'Enter the reset token',
        passwordMin: 'Password must be at least 12 characters',
        passwordUpper: 'Must include an uppercase letter',
        passwordLower: 'Must include a lowercase letter',
        passwordDigit: 'Must include a digit',
        confirmRequired: 'Enter password confirmation',
        confirmMismatch: 'Passwords do not match',
      },
      error: {
        generic: 'An error occurred during reset',
      },
    },
    settings: {
      eyebrow: 'Control center',
      title: 'Settings',
      description: 'Manage account and security settings',
      tabs: { account: 'Account', security: 'Security', tokens: 'Tokens', llm: 'LLM', data: 'Data', audit: 'Audit', mcp: 'MCP' },
      pending: {
        loadingTitle: 'Loading settings',
        loadingDesc: 'Account and security settings will appear once your session is restored.',
        redirectTitle: 'Redirecting to login',
        redirectDesc: 'Settings are only available after logging in.',
      },
      account: {
        infoTitle: 'Account Info',
        emailLabel: 'Email',
        passwordChangeTitle: 'Change Password',
        currentPassword: 'Current password',
        newPassword: 'New password',
        confirmPassword: 'Confirm new password',
        submit: 'Change',
        passwordChanged: 'Password has been changed',
        socialLoginTitle: 'Social Login',
        connected: 'Connected',
        socialDesc: ' account is linked. Set a password before disconnecting.',
        disconnected: 'Disconnected. Please log in with your password.',
        disconnect: 'Disconnect',
        disconnecting: 'Processing...',
        validation: {
          allFieldsRequired: 'All fields are required',
          passwordMismatch: 'New passwords do not match',
          passwordMin: 'Password must be at least 12 characters',
          changeFailed: 'Failed to change password',
          disconnectFailed: 'Failed to disconnect',
        },
      },
      security: {
        title: '2FA',
        enabled: 'Enabled',
        disabled: 'Disabled',
        setupDesc: 'Enable 2FA with a TOTP app (Google Authenticator, etc.)',
        enableButton: 'Enable 2FA',
        setupGuide: 'Scan the QR code, then enter the verification code',
        secretKey: 'Manual key',
        codeLabel: 'Verification code',
        confirmButton: 'Confirm',
        backupTitle: 'Save your backup codes in a safe place',
        disableButton: 'Disable 2FA',
        disablePasswordLabel: 'Current password',
        disableCodeLabel: 'TOTP code',
        disableSubmit: 'Disable',
        cancelButton: 'Cancel',
        error: {
          setupFailed: '2FA setup failed',
          confirmFailed: 'Code verification failed',
          disableFailed: 'Disable failed',
        },
      },
      audit: {
        desc: 'View session activity and access logs',
        viewLog: 'View Audit Log',
        recentTitle: 'Recent activity (last 20)',
        viewAll: 'View all',
        empty: 'No activity recorded',
      },
      dataExport: {
        title: 'Export my data',
        desc: 'Download a single zip with the projects and memories piLoci has organized for you. Use it to migrate to another server or to keep a backup.',
        export: 'Export',
        exporting: 'Exporting...',
        error: {
          generic: 'Failed to export',
          throttled: 'Please try again shortly',
        },
      },
      dataImport: {
        title: 'Import',
        desc: 'Upload a zip downloaded from another piLoci to quietly merge it into the current account. Projects with the same name are renamed automatically.',
        archiveLabel: 'Archive (.zip)',
        reembedToggle: 'Recompute embeddings if the embedding model differs',
        import: 'Import',
        importing: 'Importing...',
        result: {
          projects: 'projects',
          renamed: 'renamed',
          memories: 'memories',
          unit: '',
          reembedded: ' · re-embedded',
        },
        error: {
          missingFile: 'Choose a .zip file to import',
          embeddingMismatch: 'The exporting server uses a different embedding model. Enable re-embedding and try again.',
          tooLarge: 'File is too large. Split it into smaller exports.',
          throttled: 'Please try again shortly',
          generic: 'Failed to import',
        },
      },
      mcp: {
        title: 'MCP Configuration',
        copy: 'Copy',
        copied: 'Copied',
      },
    },
    appShell: {
      locale: { trigger: 'Language', title: 'Choose a language', desc: 'Pick the language used across the interface.' },
      nav: { dashboard: 'Dashboard', projects: 'Projects', chat: 'Chat' },
      dropdown: { settings: 'Settings', activity: 'Activity', admin: 'Admin', logout: 'Log Out' },
      footer: { privacy: 'Privacy Policy', terms: 'Terms of Service' },
    },
    chat: {
      eyebrow: 'Memory chat',
      title: 'Pull memories with chat',
      subtitle: 'Answers come from saved memories. Use the citation numbers to inspect sources.',
      projectSelectAria: 'Select project',
      projectPlaceholder: 'Project',
      noProjects: 'No projects yet',
      pendingTitle: 'Checking session',
      pendingDesc: 'Preparing your conversation.',
      redirectTitle: 'Redirecting to login',
      redirectDesc: 'Auth state confirmed. Safely moving to the login page.',
      emptyTitle: 'What are you looking for?',
      emptyDesc: 'Answers only draw from saved memories. A natural-language question is enough.',
      examples: [
        'What was decided this week?',
        'What OAuth issues came up?',
        'Summarize the patterns I keep using.',
      ],
      thinking: 'Looking through memories…',
      errorPrefix: 'Error',
      placeholderDisabled: 'Select a project first',
      placeholderActive: 'Ask anything',
      input: {
        questionAria: 'Question input',
        sendAria: 'Send',
        stopAria: 'Stop',
        closeErrorAria: 'Close',
        micStartAria: 'Ask by voice',
        micStopAria: 'Stop voice input',
        micRecordingTitle: 'Recording… click to stop',
        micIdleTitle: 'Voice input (Korean)',
      },
      dictation: {
        notAllowed: 'Microphone permission was denied. Allow mic access in your browser/system and try again.',
        audioCapture: 'No microphone found. Check your input device.',
        network: 'Could not connect to the speech recognition service. Check your network.',
        noSpeech: 'No voice detected. Please try again.',
        aborted: 'Voice input was stopped.',
        insecureContext: 'Voice input only works over HTTPS.',
        unknown: 'Speech recognition error',
        consoleHint: 'Check the console for details.',
        startFailed: 'Could not start voice recognition.',
        startRetry: 'Could not start voice recognition. Please try again shortly.',
        silentFailure: 'No voice was recognized. Check your microphone permission.',
      },
    },
    device: {
      pendingTitle: 'Preparing device approval page',
      pendingDesc: 'Loading the verification code screen.',
      readyDesc: 'Confirming your login state, then showing the device approval screen.',
      cardTitle: 'Device approval',
      intro1: 'Enter the 8-character code shown by ',
      intro2: ' in your terminal — once approved, the device receives a token automatically.',
      codeLabel: 'Verification code',
      approveButton: 'Approve this device',
      approving: 'Approving…',
      denyButton: 'Deny',
      successMessage: 'Approved. Return to your terminal — it will continue automatically.',
      deniedMessage: 'Request denied. Generate a new code and try again.',
      footer1: ' or ',
      footer2: ' issues the code.',
      targets: {
        title: 'Install targets',
        hint: 'We merge the piloci MCP server only into the global config of the clients you tick. At least one is required.',
        selectAll: 'All',
        clearAll: 'Clear',
        emptyError: 'Pick at least one install target.',
        list: [
          { kind: 'claude', label: 'Claude Code', path: '~/.claude/plugins/piloci/' },
          { kind: 'opencode', label: 'OpenCode', path: '~/.config/opencode/plugins/piloci.ts' },
          { kind: 'cursor', label: 'Cursor', path: '~/.cursor/mcp.json' },
          { kind: 'gemini', label: 'Gemini CLI', path: '~/.gemini/settings.json' },
          { kind: 'windsurf', label: 'Windsurf', path: '~/.codeium/windsurf/mcp_config.json' },
          { kind: 'codex', label: 'Codex CLI', path: '~/.codex/config.toml' },
          { kind: 'antigravity', label: 'AntiGravity', path: '~/.antigravity/mcp.json' },
          { kind: 'zed', label: 'Zed', path: '~/.config/zed/settings.json' },
        ],
      },
      error: {
        invalidFormat: 'Code format is ABCD-1234.',
        serverPrefix: 'Server returned',
        serverSuffix: 'response.',
        network: 'Network error',
      },
    },
    authLayout: {
      heading1: 'Give your AI',
      heading2: 'new memories to work with',
      description: 'piLoci provides project-isolated memory spaces so your AI never loses context.',
      privacyLink: 'Privacy Policy',
      termsLink: 'Terms of Service',
    },
    authProviders: {
      kakao: 'Continue with Kakao',
      naver: 'Continue with Naver',
      google: 'Continue with Google',
      github: 'Continue with GitHub',
    },
    dashboard: {
      eyebrow: 'Memory workspace',
      title: 'Dashboard',
      subtitle: 'A quick look at recent activity and how memories are flowing.',
      newProject: 'New Project',
      createTitle: 'Create New Project',
      slugLabel: 'Slug *',
      nameLabel: 'Name *',
      descLabel: 'Description',
      descPlaceholder: 'Project description',
      cancel: 'Cancel',
      creating: 'Creating...',
      create: 'Create',
      validation: {
        slugAndNameRequired: 'Please enter both slug and name',
        createFailed: 'Failed to create project',
      },
      stats: { projects: 'Projects', totalMemories: 'Total Memories', totalKnacks: 'Total Patterns', status: 'Status', syncing: 'Syncing', ready: 'Ready' },
      summary: {
        activityTitle: 'Recent activity',
        activityEmpty: 'No sessions yet',
        recentMemoriesTitle: 'Recent memories',
        recentMemoriesEmpty: 'No memories yet',
        topKnacksTitle: 'Top patterns',
        topKnacksEmpty: 'No patterns yet',
        recentSessionsTitle: 'Recent sessions',
        recentSessionsEmpty: 'No sessions yet',
        topTagsTitle: 'Frequent tags',
        topTagsEmpty: 'No tags',
        viewAll: 'View all',
        viewProject: 'Open project',
        sessionMemories: '{count} memories',
        sessionPending: 'Analyzing',
        cols: {
          memory: 'Memory',
          project: 'Project',
          tags: 'Tags',
          when: 'When',
          then: 'Then',
          domain: 'Domain',
          count: 'Count',
          tag: 'Tag',
          status: 'Status',
          time: 'Time',
        },
      },
      empty: { title: 'No projects yet', create: 'Create Project' },
      error: { title: 'Failed to load projects', retry: 'Retry' },
      pending: { title: 'Checking session', desc: 'Loading account information needed for the dashboard.' },
      redirect: { title: 'Redirecting to login', desc: 'Verified auth state and safely redirecting to the login page.' },
    },
    projects: {
      eyebrow: 'Project memory',
      breadcrumb: 'Dashboard',
      notes: 'Notes',
      nodes: 'Nodes',
      edges: 'Edges',
      tags: 'Tags',
      knacks: 'Patterns',
      sessions: 'Sessions',
      memories: 'Memories',
      lastActive: 'Last activity',
      lastAnalyzed: 'Last analyzed',
      neverActive: 'No activity yet',
      cardMemories: 'memories',
      cardKnacks: 'patterns',
      tabMemories: 'Memories',
      tabKnacks: 'Patterns',
      tabSessions: 'Raw sessions',
      knackDomain: 'Domain',
      knackConfidence: 'Confidence',
      knackCount: 'Observed',
      knackEvidence: 'Evidence',
      knacksEmpty: 'No patterns extracted yet',
      sessionMeta: '{kb} KB · {client}',
      sessionStatusProcessed: '{count} memories extracted',
      sessionStatusPending: 'Pending analysis',
      sessionStatusFailed: 'Analysis failed',
      sessionsEmpty: 'No sessions ingested yet',
      viewTranscript: 'View transcript',
      hideTranscript: 'Hide',
      transcriptLoading: 'Loading...',
      transcriptFailed: 'Failed to load',
      openButton: 'Open',
      editAria: 'Edit project',
      deleteAria: 'Delete project',
      editTitle: 'Edit project',
      editSlugLabel: 'Slug',
      editSlugHelp: 'Slug keys memory and token mappings — it cannot be changed.',
      editNameLabel: 'Name *',
      editDescLabel: 'Description',
      editDescPlaceholder: 'Project description',
      editCancel: 'Cancel',
      editSaving: 'Saving...',
      editSave: 'Save',
      editNameRequired: 'Name cannot be empty',
      editSaveFailed: 'Failed to save',
      deleteTitle: 'Delete',
      deleteDesc: 'Deleting this project removes all linked memories and notes. This cannot be undone.',
      deleteConfirm: 'Delete',
      noNotes: 'No notes',
      quickSelect: 'Quick Select',
      quickSelectDesc: 'Click a number to jump to the corresponding note.',
      mcpConfig: 'MCP Configuration',
      pending: { title: 'Locating project', desc: 'Finding the project to open. If not found, you\'ll be redirected to the dashboard.' },
    },
    audit: {
      eyebrow: 'Security timeline',
      title: 'Activity Log',
      subtitle: 'Security events and access records',
      filter: 'Filter',
      // Keys MUST match the action string written to audit_logs.action by the
      // backend (see piloci.auth.local + piloci.api.routes._admin_audit).
      actions: {
        all: 'All',
        signup: 'Signup',
        login_success: 'Login Success',
        login_fail: 'Login Failed',
        login_fail_totp: '2FA Failed',
        password_reset: 'Password Reset',
        token_created: 'Token Created',
        token_revoked: 'Token Revoked',
        project_created: 'Project Created',
        project_deleted: 'Project Deleted',
        admin_toggle_admin: 'Admin Role Changed',
        admin_toggle_active: 'Account Activated/Deactivated',
        admin_delete_user: 'User Deleted',
      },
      table: { time: 'Time', event: 'Event', ip: 'IP', userAgent: 'User Agent' },
      empty: { error: 'Failed to load activity log', noLogs: 'No events recorded' },
      pagination: { prev: 'Previous', next: 'Next', page: 'Page' },
      pending: { title: 'Preparing activity log', desc: 'Restoring login state and filter settings before displaying activity log.' },
      redirect: { title: 'Redirecting to login', desc: 'Activity log is a protected page. Redirecting to login.' },
    },
    tokenManager: {
      desc: 'Access piLoci from external clients using API tokens',
      issue: 'Issue',
      issuing: 'Issuing...',
      tokenCreated: 'Token Issued',
      tabs: { token: 'Token', mcpServer: 'MCP Server', install: 'Claude Install', claudeMd: 'CLAUDE.md' },
      tokenWarning: 'This token cannot be viewed again. Copy it now.',
      mcpInstructions: '. Paste the content below. If the file exists, only the mcpServers key will be merged.',
      mcpNote: 'After restarting Claude Code, the memory, recall, and recommend tools will be automatically activated.',
      quickInstallTitle: 'One-line install (uvx)',
      quickInstallDesc: 'A single command stamps hook.py, config.json, and merges into ~/.claude/settings.json. The install code is single-use and expires in 10 minutes.',
      quickStep1: '① Copy the command',
      quickStep1Desc: 'Use the copy button on the right of the box below. The command embeds your one-time install code.',
      quickStep2: '② Paste and run in your terminal',
      quickStep2Desc: 'Requires uvx (`pip install uv` if missing). On run it sets up ~/.config/piloci and merges ~/.claude/settings.json for you.',
      quickStep3: '③ Restart Claude Code',
      quickStep3Desc: 'After the restart the memory / recall / recommend MCP tools become available.',
      quickInstallNoCode: 'No install code was issued for this token. Issue a new token to get the auto-install command.',
      manualInstallToggle: 'Show manual install',
      manualInstallHide: 'Hide manual install',
      manualInstallNote: 'Use this only when the auto-install script is blocked or unavailable.',
      hookStep1: '① Download Script (once)',
      hookStep1Desc: 'Install once — no reinstall needed when token rotates.',
      hookStep2: '② Save config.json',
      hookStep2Desc: 'Save the content below to ~/.config/piloci/config.json. Update only this file when token rotates.',
      hookStep3: '③ Configure settings.json',
      hookStep3Desc: 'Merge into the hooks key in ~/.claude/settings.json.',
      claudeMdInstructions: 'Paste into your project\'s CLAUDE.md. Claude will automatically load past memories at session start and save important content with the memory tool during conversations.',
      formName: 'Token Name',
      formNamePlaceholder: 'e.g. Claude Code',
      formScope: 'Scope',
      scopeUser: 'All User',
      scopeProject: 'Project (auto-generates MCP + SessionStart Hook config)',
      formProject: 'Project',
      selectProject: 'Select',
      noTokens: 'No tokens issued',
      formExpire: 'Validity',
      expireOptions: {
        d30: '30 days',
        d90: '90 days',
        d180: '6 months',
        d365: '1 year',
        none: 'No expiry',
      },
      tableHeaders: { name: 'Name', scope: 'Scope', issued: 'Issued', lastUsed: 'Last Used', expires: 'Expires' },
      expiresNone: 'No expiry',
      expired: 'Expired',
      confirmRevoke: 'Revoke this token?',
      cancel: 'Cancel',
      mcpConfigFor: 'MCP Config —',
      envHint: 'Use this when managing tokens via environment variables.',
      notInstalled: 'Not installed',
      installedOn: 'Installed',
      loadFailed: 'Failed to load tokens',
      retry: 'Retry',
      mcpClaudeHint: 'Claude Desktop / Claude Code / Cursor — .mcp.json or claude_desktop_config.json',
      mcpClaudeOr: 'or',
      mcpOpencodeHint: 'OpenCode — opencode.json',
      mcpOpencodeRemote: 'use',
      crossPlatformLabel: 'Windows / cross-platform (uvx)',
      tokenPlaceholder: '<PASTE_TOKEN_HERE>',
      tokenPasteNotice: 'Tokens are only shown at issue time. Replace <PASTE_TOKEN_HERE> in the snippets below with the issued token.',
    },
    llm: {
      heading: 'External LLM fallback',
      description: 'When local Gemma is busy, falls back to external OpenAI-compatible models in priority order.',
      add: 'Add',
      addTitle: 'Add external LLM',
      editTitle: 'Edit external LLM',
      deleteConfirmDesc: 'This removes the external LLM fallback from your list. The API key is deleted too.',
      removeButton: 'Remove',
      empty: 'No external LLM registered. Using Gemma only.',
      loadFailed: 'Failed to load list.',
      enabled: 'Enabled',
      disabled: 'Disabled',
      priorityLabel: 'Priority {priority}',
      modelLabel: 'Model',
      keyLabel: 'Key',
      ariaToggleOn: 'Enable',
      ariaToggleOff: 'Disable',
      ariaEdit: 'Edit',
      ariaDelete: 'Delete',
      form: {
        nameLabel: 'Name *',
        baseUrlLabel: 'Base URL *',
        baseUrlHelp: 'Base of the OpenAI-compatible endpoint. /v1/chat/completions is appended automatically.',
        modelLabel: 'Model *',
        apiKeyLabel: 'API key',
        apiKeyEditNote: 'Leave blank to keep current key',
        priorityLabel: 'Priority',
        priorityHelp: 'Lower = tried first',
        enabledLabel: 'Enabled',
        cancel: 'Cancel',
        saving: 'Saving...',
        save: 'Save',
        addAction: 'Add',
        allFieldsRequired: 'Name, Base URL, Model, API key all required',
        addFailed: 'Failed to add',
        saveFailed: 'Failed to save',
      },
    },
    vaultNote: {
      tags: 'tags',
      noPreview: 'No preview available',
      selectNote: 'Select a note',
      linkedNotes: 'Linked Notes',
    },
    projectCard: {
      workspace: 'Project Workspace',
      memories: 'memories',
      open: 'Open',
    },
    themeToggle: { toLightAriaLabel: 'Switch to light', toDarkAriaLabel: 'Switch to dark' },
};

const copy: Record<Locale, CopyShape> = { ko, en };

export function getCopy(locale: Locale = defaultLocale): CopyShape {
  return copy[locale];
}
