export const locales = ['ko', 'en'] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = 'ko';

const copy = {
  ko: {
    metadata: { description: '라즈베리파이를 위한 고성능 MCP 메모리 엔진' },
    common: { brandName: 'piLoci', login: '로그인', signup: '시작하기', badge: 'Self-Hosted' },
    landing: {
      quotes: [
        '"기억은 지혜의 어머니이다" — 아이스킬로스',
        '"기억은 과거의 보물이자 미래의 길잡이다"',
        '"잊혀진 것은 존재하지 않는 것이나 같다" — 괴테',
        '"우리는 기억하는 만큼만 존재한다" — 파스칼',
        '"기억은 마음의 금고이다" — 토마스 풀러',
        '"과거를 기억하는 자만이 미래를 열 수 있다"',
        '"기억이 없으면 경험은 불가능하다" — 칸트',
        '"가장 위대한 재산은 기억이다" — 키티론',
        '"기억은 영혼의 그림자이다" — 호메로스',
        '"망각보다 기억이 더 많은 것을 만든다" — 벤자민 프랭클린',
        '"우리의 기억이 우리의 정체성이다" — 존 로크',
        '"기억은 시간의 파수꾼이다" — 에라스무스',
        '"잊지 않는 것은 곧 배우는 것이다"',
        '"기억은 모든 것의 어머니이자 보유자이다" — 아우구스티누스',
        '"좋은 기억은 지혜의 한 부분이다" — 세네카',
        '"기억 없는 마음은 거주자 없는 집과 같다"',
        '"과거를 기억하지 못하면 그것을 반복하게 된다" — 산타야나',
        '"기억은 경험의 창고이자 지혜의 원천이다"',
        '"가장 생생한 기억이 가장 깊은 상처를 남긴다"',
        '"망각은 자비이고, 기억은 축복이다"',
        '"기억은 지식의 보물이자 생각의 감독이다" — 키케로',
        '"모든 것은 기억에서 시작된다"',
        '"경험은 기억이라는 이름으로 살아간다"',
        '"기억하는 자는 결코 혼자가 아니다"',
        '"기억은 존재의 근원이다" — 마르셀 프루스트',
        '"기억이 강한 자는 삶도 강하다"',
        '"과거를 기억하는 것이 현재를 이해하는 길이다"',
        '"기억은 사랑의 가장 오래가는 증거이다"',
        '"배움은 기억의 또 다른 이름이다" — 플라톤',
        '"기억은 영원히 살아 숨쉬는 유일한 것이다"',
        '"기억은 잃어버린 시간을 되찾는 열쇠이다" — 프루스트',
        '"기억은 정체성의 핵심이다"',
        '"진정한 기억은 마음속에 새겨진다"',
        '"기억은 우리가 진정 누구인지 말해준다"',
        '"지혜는 기억의 결정체이다"',
        '"기억은 존재의 연속성이다" — 데이비드 흄',
        '"기억은 마음의 거울이다" — 톨스토이',
        '"기억 속에 사는 자는 죽지 않는다"',
        '"기억은 가장 충실한 친구이다" — 헨리 워드 비처',
        '"기억은 과거와 현재를 잇는 다리이다"',
        '"가장 소중한 것은 결코 잊히지 않는다"',
        '"기억은 경험을 지혜로 변환하는 연금술이다"',
        '"기억은 우리 모두의 내면의 서가이다" — 몽테뉴',
        '"좋은 기억력은 좋은 마음의 증거이다" — 아리스토텔레스',
        '"기억은 삶의 방아쇠이다" — 니체',
        '"기억이 있는 곳에 희망이 있다"',
        '"기억은 경험의 어머니이다" — 레오나르도 다빈치',
        '"과거를 기억하라, 그것이 미래의 밑거름이다" — 키케로',
        '"기억은 우리가 소유한 가장 영원한 소유물이다"',
        '"망각은 죽음이고, 기억은 부활이다" — 보들레르',
      ],
      titleLines: ['KNOWLEDGE MEMORY', 'FOR YOUR AI CORE'],
      descriptionLines: [
        'piLoci는 라즈베리파이와 같은 저전력 환경에서도 작동하도록 토큰, I/O, LLM 호출을 아끼는 MCP 기반 셀프 호스트 메모리 서버입니다.',
      ],
      terminal: {
        title: 'piLoci MCP',
        examples: [
          {
            q: '어제 진행했던 프로젝트 뭐였지?',
            tool: 'recall',
            toolArgs: '{"query": "어제 진행 프로젝트", "limit": 3}',
            result: 'preview 3개 — [piloci/스캐폴딩] [piloci/MCP 라우팅] [piloci/인증]',
            a: '어제 piLoci 프로젝트를 진행하셨습니다. MCP 서버 라우팅을 /mcp 프리픽스로 리팩토링하고, SSE 전송 레이어를 Starlette 서브앱으로 마운트하는 작업을 하셨네요.',
          },
          {
            q: '어디까지 했더라… 진행 상황 알려줘',
            tool: 'recall',
            toolArgs: '{"query": "현재 진행 상태", "limit": 5}',
            result: 'preview 5개 — 메모리 847개 중 관련 항목만 발췌',
            a: '현재 piLoci 프로젝트는 랜딩 페이지 UI 개선 중입니다. 다크 테마 violet 톤 적용, MCP 라우팅 /mcp로 리팩토링 완료. 다음: Docker 프로덕션 설정.',
          },
          {
            q: '그때 논의한 인증 방식 다시 알려줘',
            tool: 'recall',
            toolArgs: '{"query": "인증 auth 방식 토큰", "limit": 3}',
            result: 'preview 3개 — [auth 라우트] [2FA 설정] [토큰 스코프]',
            a: 'JWT 세션 + TOTP 2FA 이중 인증, argon2id 비밀번호 해시, API 토큰은 프로젝트 스코프 기반이었어요. refresh 토큰은 httpOnly 쿠키에 저장하기로 했습니다.',
          },
          {
            q: '저번에 읽다 만 책 제목이 뭐였지?',
            tool: 'recall',
            toolArgs: '{"query": "책 독서 목록 추천", "limit": 5}',
            result: 'preview 5개 — [독서 노트] [추천 도서] [완독 목록] [서재] [북클럽]',
            a: '"사피엔스"를 7장까지 읽으셨고, 그 다음으로 "Thinking, Fast and Slow"가 대기 중이었어요. 작년에 추천받은 "디에고 벨라스케스 평전"도 있네요.',
          },
          {
            q: '다음 주 미팅에 뭐 준비해야 하지?',
            tool: 'recall',
            toolArgs: '{"query": "미팅 회의 준비 agenda", "limit": 3}',
            result: 'preview 3개 — [주간 미팅] [스프린트 리뷰] [백로그]',
            a: '화요일 스프린트 리뷰: 랜딩 페이지 데모, Docker 배포 진행 상황 발표 예정이에요. 목요일 백로그 그루밍에서 v0.3 마일스톤 우선순위를 정하기로 했습니다.',
          },
          {
            q: '내가 어떤 커피 좋아하는지 알아?',
            tool: 'recall',
            toolArgs: '{"query": "커피 취향 맛 선호", "limit": 3}',
            result: 'preview 3개 — [취향 프로필] [카페 메모] [선물 리스트]',
            a: '산미 있는 라이트 로스트 선호, 특히 에티오피아 예가체프 종류를 좋아하세요. 블루보틀 싱글오리진이 단골이고, 설탕·시럽은 안 넣는 블랙파베리스타.',
          },
          {
            q: '오늘 장 봐야 할 거 리마인드 해줘',
            tool: 'recall',
            toolArgs: '{"query": "장보기 식료품 할 일", "limit": 5}',
            result: 'preview 5개 — [장보기 리스트] [레시피] [식단] [냉장고 재고] [할인]',
            a: '우유, 계란, 방울토마토, 아보카도가 떨어졌어요. 저번에 저장해둔 파스타 레시피로 올리브 오일도 사야 하고, 페스코 약속한 생선도 있네요.',
          },
          {
            q: '이번 프로젝트 제약사항 정리해줘',
            tool: 'recall',
            toolArgs: '{"query": "제약사항 constraints 보안", "limit": 5}',
            result: 'preview 5개 — [CLAUDE.md] [routes.py] [sse.py] [.env.example] [security]',
            a: '수집된 제약사항: ① argon2id만 사용 (bcrypt 금지) ② raw SQL 금지, ORM만 ③ JWT secret 환경변수로만 ④ (user_id, project_id) 필터 필수 ⑤ orjson 사용',
          },
          {
            q: '삼촌 생신이 언제였지? 선물 뭐 샀지?',
            tool: 'recall',
            toolArgs: '{"query": "삼촌 생신 선물 가족", "limit": 3}',
            result: 'preview 3개 — [가족 기념일] [선물 기록] [일정]',
            a: '삼촌 생신은 5월 12일이에요. 작년에는 몽블랑 만년필을 드렸고, 올해는 아직 정하지 않으셨어요. 3월에 보셨을 때 건강이 좀 안 좋으셨다고 했던 거 같아요.',
          },
          {
            q: '저번 여행 일정 다시 보여줘',
            tool: 'recall',
            toolArgs: '{"query": "여행 일정 계획 후쿠오카", "limit": 5}',
            result: 'preview 5개 — [여행 일정] [맛집 리스트] [숙소] [항공] [지출]',
            a: '후쿠오카 3박 4일: 1일차 텐진·야타이, 2일차 다자이후·운젠 온천, 3일차 하카타 구시탄·캐널시티. 숙소는 하카타역 도보 5분 호텔이었어요.',
          },
          {
            q: 'Docker 빌드가 자꾸 실패하는데 로그 확인해줘',
            tool: 'recall',
            toolArgs: '{"query": "Docker 빌드 에러 실패 로그", "limit": 3}',
            result: 'preview 3개 — [Dockerfile 수정] [CI 로그] [arm64 이슈]',
            a: '지난번에도 같은 문제가 있었어요. 멀티아키 빌드에서 arm64 타겟의 pip 캐시 레이어가 꼬이는 이슈였습니다. --no-cache로 빌드하니 해결됐었고요.',
            followUp: {
              q: '그때 수정했던 Dockerfile 내용 적용해줘',
              tool: 'memory',
              toolArgs: '{"action": "save", "content": "Dockerfile arm64 캐시 수정 사항 반영 완료", "tags": ["docker", "fix", "arm64"]}',
              result: '저장 완료 — Dockerfile arm64 빌드 수정',
              a: 'Dockerfile에 캐시 관련 수정 사항을 반영했습니다. 다시 빌드해볼까요?',
            },
          },
        ],
      },
      stats: {
        latency: '2ms',
        reduction: '80%+',
        uptime: '100%',
        latencyLabel: '벡터 검색',
        reductionLabel: '토큰 절감',
        uptimeLabel: '로컬 운영',
      },
      sections: {
        intro: {
          title: '소개',
          content: 'piLoci는 라즈베리파이와 같은 저전력 환경에서도 작동하도록 토큰, I/O, LLM 호출을 아끼는 MCP 기반 셀프 호스트 메모리 서버입니다.',
        },
        features: {
          title: '아키나 다운힐의 AE86처럼, 무게는 줄이고 속도는 빠르게',
          subtitle: 'piLoci는 라즈베리파이와 같은 저전력 환경에서도 작동하도록 설계되어 토큰, I/O, LLM 호출을 최소화한 MCP 메모리 서버입니다.',
          list: [
            { title: '맥락 격리', desc: '프로젝트별 메모리 분리. 맥락 섞임 방지.' },
            { title: 'AST 기반 추출', desc: 'Tree-sitter로 코드 구조를 정밀하게 보존.' },
            { title: '2ms 벡터 검색', desc: 'Pi 5에서도 2ms 이내 시멘틱 검색.' },
            { title: '100% 로컬', desc: '클라우드 의존성 없이 외부 유출 걱정 없는 환경.' },
            { title: '자동 큐레이션', desc: '대화에서 핵심 정보를 자동 추출·저장.' },
            { title: '프리뷰 우선 recall', desc: 'excerpt 먼저, 필요할 때만 전문 로드.' },
            { title: 'Vault 워크스페이스', desc: '노트·그래프·태그로 메모리를 한눈에.' },
            { title: 'Telegram 요약', desc: '의미 있는 세션만 요약 전송.' },
            { title: 'MCP 표준 호환', desc: 'Claude, Cursor, Windsurf 등 바로 연결.' },
          ]
        },
        quickStart: {
          title: '빠른 시작',
          installTitle: '1. uvx를 이용한 설치',
          installDesc: '별도의 복잡한 설정 없이 다음 명령어로 즉시 서버를 실행할 수 있습니다.',
          setupTitle: '2. 백엔드 구성 (.env)',
          setupDesc: '환경 변수를 통해 SQLite 경로 및 인덱싱 엔진을 자유롭게 설정하세요.',
        },
        capabilities: {
          title: '반드시 필요한 툴만, 극한의 미니멀리즘',
          desc: 'LLM의 프롬프트 맥락을 해치지 않도록, 최소한의 툴 개수로 최대한의 효율을 추구합니다.',
          note: 'LLM의 프롬프트 맥락을 해치지 않도록, 최소한의 툴 개수로 최대 효율을 추구합니다.',
          list: [
            { name: 'memory', desc: '새로운 정보나 프로젝트의 맥락을 영구 메모리에 저장하거나 오래된 항목을 제거합니다.' },
            { name: 'recall', desc: '기본은 preview만 반환하고, 필요할 때만 선택적으로 전문이나 markdown export를 가져옵니다.' },
            { name: 'listProjects', desc: '5분 캐시된 프로젝트 목록을 빠르게 가져오고, 필요하면 refresh=true로 강제 갱신합니다.' },
          ]
        },
        pricing: {
          title: '투명한 오픈소스, 완전한 자유',
          desc: [
            'piLoci는 모든 소스코드가 공개된 오픈소스 프로젝트입니다.',
            '누구나 함께 참여하고 개선할 수 있습니다.',
          ],
          features: [
            '무제한 프로젝트 생성',
            '로컬 SQLite + LanceDB',
            '상업적 이용 가능 (MIT)',
            '개인 정보 추적 0%',
            '옵시디언 호환 워크스페이스',
            '팀 단위 멀티유저 지원',
            '완전한 셀프 호스트 (Docker)',
            'Google OAuth + TOTP 2FA',
          ],
          engineering: {
            title: '놀고 있는 라즈베리파이에게 맡기세요!',
            desc: '모든 아키텍처 결정은 "제로 코스트, 최소 리소스"를 기준으로 내려졌습니다.',
            items: [
              { label: 'LanceDB', desc: '클라우드 벡터 DB 불필요. 로컬 파일 기반 임베딩 저장소.' },
              { label: 'SQLite', desc: '외부 RDBMS 없이 모든 메타데이터를 로컬에서 처리.' },
              { label: 'fastembed (ONNX)', desc: 'GPU·torch 없이 CPU만으로 384차원 임베딩 생성.' },
              { label: 'LRU 임베딩 캐시', desc: '동일 텍스트 재연산 방지. 반복 쿼리는 즉시 반환.' },
              { label: 'Preview-first recall', desc: '긴 검색 결과를 바로 모델에 쏟아붓지 않고 preview→fetch→file로 단계적으로 로드.' },
              { label: 'orjson', desc: '표준 json 대비 2-3배 빠른 직렬화. Pi의 느린 CPU에서 유의미.' },
              { label: 'Telegram session summary', desc: '백엔드 메타데이터만으로 긴 작업 세션만 골라서 알림. LLM 토큰 추가 소모 0.' },
            ],
          },
        }
      },
      footer: '© piLoci 2026. Husband of Rebekah.',
    },
    privacy: {
      title: '개인정보 처리방침',
        subtitle: 'piLoci 개인정보 처리방침',
        preamble: '정보통신망 이용촉진 등에 관한 법률 등 관련 법률에 의한 개인정보 보호규정 및 가이드라인을 준수하고 있습니다.',
        sections: [
          {
            title: '1. 개인정보의 수집 항목',
            content: '원활한 서비스 이용과 고객과의 소통을 위해 수집합니다.',
            items: ['필수항목: 이메일', '자동수집항목: 활동 기록(감사 로그), 쿠키 등', '활동 기록이란? 로그인 시점, API 호출 기록, 프로젝트 생성/수정 이력 등이 포함되는 사용자 로그입니다.'],
          },
          {
            title: '2. 개인정보 보유 및 이용기간',
            content: '',
            items: ['가입 회원정보는 탈퇴 시 즉시 파기됩니다.', '프로젝트 데이터 및 메모리는 사용자가 직접 삭제할 때까지 보관됩니다.', '감사 로그는 계정 활성 상태 동안 보관됩니다.'],
          },
          {
            title: '3. 개인정보의 수집·이용 목적',
            content: '',
            items: [
              '이메일: 회원 가입 시 사용자 확인, 중복 가입 방지, 부정 이용 방지',
              '비밀번호: Argon2id 해시로 단방향 암호화하여 저장하며, 원문은 수집하지 않습니다.',
              '활동 기록, 접속 기록: 부정 이용 방지, 비인가 사용 방지, 서비스 품질 개선',
            ],
          },
          {
            title: '4. 개인정보의 제3자 제공',
            content: '',
            items: ['piLoci는 로컬 우선(Local-first) 철학에 따라 모든 데이터를 사용자의 장치에만 저장합니다.', '어떠한 개인정보도 외부 서버나 제3자에게 전송하지 않습니다.', '클라우드 동기화 기능 사용 시에만 사용자가 명시적으로 선택한 데이터가 전송됩니다.'],
          },
          {
            title: '5. 개인정보의 파기',
            content: '',
            items: ['회원 탈퇴 시 즉시 모든 개인정보를 파기합니다.', '비밀번호는 해시 형태로만 저장되므로 복원할 수 없습니다.', '서비스 종료 시 모든 사용자 데이터를 영구 삭제합니다.'],
          },
          {
            title: '6. 개인정보 보호를 위한 기술적·관리적 조치',
            content: '',
            items: ['비밀번호: Argon2id 단방향 해시 암호화', '인증: JWT 기반 세션 관리', 'API 접근: 프로젝트별 격리된 스코프 토큰', '네트워크: HTTPS/TLS 암호화 통신', '데이터베이스: 사용자·프로젝트 단위 접근 제어'],
          },
          {
            title: '7. 이용자의 권리',
            content: '',
            items: ['언제든지 본인의 개인정보를 열람·수정·삭제할 수 있습니다.', '서비스 내 설정 페이지에서 직접 관리 가능합니다.', '개인정보 처리에 대한 문의는 이메일로 연락 주시면 즉시 처리합니다.'],
          },
        ],
        dates: '공고일자: 2026년 1월 1일 / 시행일자: 2026년 1월 1일',
      },
  },
  en: {
    metadata: { description: 'High-performance MCP memory engine for Raspberry Pi' },
    common: { brandName: 'piLoci', login: 'Log in', signup: 'Get Started', badge: 'Self-Hosted' },
    landing: {
      quotes: [
        '"Memory is the mother of all wisdom" — Aeschylus',
        '"Memory is the treasure house of the mind"',
        '"What is forgotten does not exist" — Goethe',
        '"We exist only as much as we remember" — Pascal',
        '"Memory is the treasurer of the mind" — Thomas Fuller',
        '"Only those who remember the past can open the future"',
        '"Without memory, experience is impossible" — Kant',
        '"The greatest possession is memory" — Chiron',
        '"Memory is the shadow of the soul" — Homer',
        '"Memory creates more than oblivion ever could" — Benjamin Franklin',
        '"Our memory is our identity" — John Locke',
        '"Memory is the guardian of time" — Erasmus',
        '"Not forgetting is itself a form of learning"',
        '"Memory is the mother and keeper of all things" — Augustine',
        '"A good memory is part of wisdom" — Seneca',
        '"A mind without memory is a house without a dweller"',
        '"Those who cannot remember the past are condemned to repeat it" — Santayana',
        '"Memory is the storehouse of experience and fountain of wisdom"',
        '"The most vivid memories leave the deepest marks"',
        '"Oblivion is mercy; memory is blessing"',
        '"Memory is the treasury and guardian of all things" — Cicero',
        '"Everything begins with memory"',
        '"Experience lives on under the name of memory"',
        '"One who remembers is never truly alone"',
        '"Memory is the root of existence" — Marcel Proust',
        '"Strong memory makes a strong life"',
        '"Remembering the past is the path to understanding the present"',
        '"Memory is the most enduring evidence of love"',
        '"Learning is simply another name for memory" — Plato',
        '"Memory is the only thing that lives and breathes forever"',
        '"Memory is the key to reclaiming lost time" — Proust',
        '"Memory is the core of identity"',
        '"True memory is engraved in the heart"',
        '"Memory tells us who we really are"',
        '"Wisdom is the crystallization of memory"',
        '"Memory is the continuity of existence" — David Hume',
        '"Memory is the mirror of the mind" — Tolstoy',
        '"Those who live in memory never die"',
        '"Memory is the most faithful friend" — Henry Ward Beecher',
        '"Memory is the bridge between past and present"',
        '"The most precious things are never forgotten"',
        '"Memory is the alchemy that turns experience into wisdom"',
        '"Memory is the inner library of us all" — Montaigne',
        '"A good memory is evidence of a good mind" — Aristotle',
        '"Memory is the trigger of life" — Nietzsche',
        '"Where there is memory, there is hope"',
        '"Memory is the mother of experience" — Leonardo da Vinci',
        '"Remember the past — it is the foundation of the future" — Cicero',
        '"Memory is the most eternal possession we own"',
        '"Oblivion is death, memory is resurrection" — Baudelaire',
      ],
      titleLines: ['KNOWLEDGE MEMORY', 'FOR YOUR AI CORE'],
      descriptionLines: [
        'piLoci is a self-hosted MCP memory server built to save tokens, I/O, and LLM calls on low-power devices like Raspberry Pi.',
      ],
      terminal: {
        title: 'piLoci MCP',
        examples: [
          {
            q: 'What was I working on yesterday?',
            tool: 'recall',
            toolArgs: '{"query": "yesterday project", "limit": 3}',
            result: '3 previews — [piloci/scaffolding] [piloci/MCP routing] [piloci/auth]',
            a: 'You were working on piLoci — refactored MCP routing to /mcp prefix, mounted SSE transport as a Starlette sub-app.',
          },
          {
            q: 'Where did I leave off? Catch me up',
            tool: 'recall',
            toolArgs: '{"query": "current progress status", "limit": 5}',
            result: '5 previews — only the relevant memories from a much larger project history',
            a: 'Landing page UI in progress — dark theme violet tones applied, MCP routing refactored to /mcp. Next: Docker production setup.',
          },
          {
            q: 'Remind me of the auth approach we decided on',
            tool: 'recall',
            toolArgs: '{"query": "auth authentication token session", "limit": 3}',
            result: '3 previews — [auth routes] [2FA setup] [token scopes]',
            a: 'Dual auth: JWT sessions + TOTP 2FA, argon2id password hashing, scoped API tokens per project. Refresh tokens in httpOnly cookies.',
          },
          {
            q: 'What was that book I was reading?',
            tool: 'recall',
            toolArgs: '{"query": "book reading list recommendation", "limit": 5}',
            result: '5 previews — [reading notes] [recommendations] [finished] [library] [book club]',
            a: 'You were halfway through "Sapiens" — chapter 7. Up next: "Thinking, Fast and Slow". Also "The Art of Strategy" from last month\'s recommendation.',
          },
          {
            q: 'What do I need to prep for next week\'s meeting?',
            tool: 'recall',
            toolArgs: '{"query": "meeting prep agenda", "limit": 3}',
            result: '3 previews — [weekly standup] [sprint review] [backlog]',
            a: 'Tuesday sprint review: demo the landing page, present Docker deployment progress. Thursday backlog grooming to prioritize v0.3 milestones.',
          },
          {
            q: 'Do you remember how I like my coffee?',
            tool: 'recall',
            toolArgs: '{"query": "coffee preference taste", "limit": 3}',
            result: '3 previews — [taste profile] [cafe notes] [gift list]',
            a: 'Light roast fan — Ethiopia Yirgacheffe is your go-to. Blue Bottle single origin regular. Black, no sugar, no syrup. Definitely not a pumpkin spice person.',
          },
          {
            q: 'Remind me what to grab from the store',
            tool: 'recall',
            toolArgs: '{"query": "grocery shopping list todo", "limit": 5}',
            result: '5 previews — [shopping list] [recipes] [meal plan] [fridge inventory] [deals]',
            a: 'Running low on milk, eggs, cherry tomatoes, and avocados. That pasta recipe you saved needs olive oil too. Don\'t forget the fish from the fishmonger.',
          },
          {
            q: 'Gather the constraints for this project',
            tool: 'recall',
            toolArgs: '{"query": "constraints security requirements", "limit": 5}',
            result: '5 previews — [CLAUDE.md] [routes.py] [sse.py] [.env.example] [security]',
            a: 'Collected: ① argon2id only (no bcrypt) ② ORM only, no raw SQL ③ JWT secret via env vars ④ (user_id, project_id) filter required ⑤ orjson mandatory',
          },
          {
            q: 'When\'s my uncle\'s birthday? What did I get him?',
            tool: 'recall',
            toolArgs: '{"query": "uncle birthday gift family", "limit": 3}',
            result: '3 previews — [family dates] [gift records] [calendar]',
            a: 'Uncle\'s birthday is May 12th. Last year you got him a Montblanc fountain pen. Nothing picked out yet for this year. He mentioned health issues in March.',
          },
          {
            q: 'Show me the itinerary from my last trip',
            tool: 'recall',
            toolArgs: '{"query": "travel itinerary Fukuoka trip", "limit": 5}',
            result: '5 previews — [itinerary] [restaurants] [hotel] [flights] [expenses]',
            a: 'Fukuoka 4 days: Day 1 Tenjin & yatai, Day 2 Dazaifu & Unzen onsen, Day 3 Hakata Kushida & Canal City. Hotel was 5 min walk from Hakata Station.',
          },
          {
            q: 'Docker build keeps failing, can you check the logs?',
            tool: 'recall',
            toolArgs: '{"query": "Docker build error failure log", "limit": 3}',
            result: '3 previews — [Dockerfile fix] [CI logs] [arm64 issue]',
            a: 'Same issue last time — multi-arch build had a corrupted pip cache layer for arm64. Rebuilding with --no-cache fixed it.',
            followUp: {
              q: 'Apply the Dockerfile fix from last time',
              tool: 'memory',
              toolArgs: '{"action": "save", "content": "Dockerfile arm64 cache fix applied", "tags": ["docker", "fix", "arm64"]}',
              result: 'Saved — Dockerfile arm64 build fix',
              a: 'Applied the cache-related fix to the Dockerfile. Want me to rebuild?',
            },
          },
        ],
      },
      stats: {
        latency: '2ms',
        reduction: '80%+',
        uptime: '100%',
        latencyLabel: 'Vector Search',
        reductionLabel: 'Token Savings',
        uptimeLabel: 'Local Operation',
      },
      sections: {
        intro: {
          title: 'Introduction',
          content: 'piLoci is a self-hosted MCP memory server designed for low-power environments like Raspberry Pi — saving tokens, I/O, and LLM calls.',
        },
        features: {
          title: 'Like an AE86 on Akina Downhill — Less Weight, More Speed',
          subtitle: 'piLoci is an MCP memory server designed for low-power environments like Raspberry Pi — minimizing tokens, I/O, and LLM calls.',
          list: [
            { title: 'Context Isolation', desc: 'Per-project memory separation. No context mixing.' },
            { title: 'AST-based Extraction', desc: 'Precise code structure preservation via Tree-sitter.' },
            { title: '2ms Vector Search', desc: 'Semantic search under 2ms, even on Pi 5.' },
            { title: '100% Local', desc: 'No cloud dependency. Zero data leaks.' },
            { title: 'Auto Curation', desc: 'Extracts and stores key info from conversations.' },
            { title: 'Preview-first Recall', desc: 'Excerpts first, full text only when needed.' },
            { title: 'Vault Workspace', desc: 'Notes, graphs, and tags at a glance.' },
            { title: 'Telegram Summaries', desc: 'Only meaningful sessions get summarized.' },
            { title: 'MCP Standard', desc: 'Connect with Claude, Cursor, Windsurf, and more.' },
          ]
        },
        quickStart: {
          title: 'Quick Start',
          installTitle: '1. Installation via uvx',
          installDesc: 'Run the server immediately with the following command without complex setup.',
          setupTitle: '2. Backend Config (.env)',
          setupDesc: 'Freely configure SQLite paths and indexing engines via environment variables.',
        },
        capabilities: {
          title: 'Only What You Need — Radical Minimalism',
          desc: 'Minimal tool count by design — to preserve LLM prompt context while maximizing efficiency.',
          note: 'Minimal tool count by design — to preserve LLM prompt context while maximizing efficiency.',
          list: [
            { name: 'memory', desc: 'Save new facts or project context to memory, or remove outdated entries by ID.' },
            { name: 'recall', desc: 'Preview matches first, then selectively fetch full content or export large results to markdown.' },
            { name: 'listProjects', desc: 'Fetch the 5-minute cached project list quickly, or force a refresh when needed.' },
          ]
        },
        pricing: {
          title: 'Transparent Open Source, Total Freedom',
          desc: [
            'piLoci is fully open source — every line of code is public.',
            'Anyone can contribute and improve it together.',
          ],
          features: [
            'Unlimited Projects',
            'Local SQLite + LanceDB',
            'Commercial Use (MIT)',
            'Zero Telemetry',
            'Obsidian-compatible Workspace',
            'Multi-user Team Support',
            'Full Self-hosted (Docker)',
            'Google OAuth + TOTP 2FA',
          ],
          engineering: {
            title: 'Put Your Idle Raspberry Pi to Work!',
            desc: 'Every architectural decision was made with "zero cost, minimal resources" in mind.',
            items: [
              { label: 'LanceDB', desc: 'No cloud vector DB needed. Local file-based embedding storage.' },
              { label: 'SQLite', desc: 'No external RDBMS. All metadata handled locally.' },
              { label: 'fastembed (ONNX)', desc: 'CPU-only 384-dim embeddings. No GPU or torch required.' },
              { label: 'LRU Embedding Cache', desc: 'Skips re-computation for repeated texts. Instant on cache hit.' },
              { label: 'Preview-first recall', desc: 'Avoids dumping large search payloads into the model context unless explicitly requested.' },
              { label: 'Telegram session summary', desc: 'Backend-only session alerts for meaningful work with zero additional LLM token cost.' },
            ],
          },
        }
      },
      footer: '© piLoci 2026. Husband of Rebekah.',
    },
    privacy: {
      title: 'Privacy Policy',
      subtitle: 'piLoci Privacy Policy',
      preamble: 'We comply with personal data protection regulations and relevant guidelines.',
      sections: [
        {
          title: '1. Information We Collect',
          content: 'We collect information to provide smooth service and communication.',
          items: ['Required: Email address', 'Automatically collected: Activity logs, cookies, etc.', 'Activity logs include login times, API call records, and project creation/modification history.'],
        },
        {
          title: '2. Data Retention',
          content: '',
          items: ['Account information is deleted immediately upon account deletion.', 'Project data and memories are retained until the user deletes them.', 'Audit logs are kept while the account is active.'],
        },
        {
          title: '3. Purpose of Data Collection',
          content: '',
          items: [
            'Email: User verification, duplicate registration prevention, fraud prevention',
            'Password: Stored using Argon2id one-way hash encryption. The plaintext is never collected.',
            'Activity and access logs: Fraud prevention, unauthorized use prevention, service improvement',
          ],
        },
        {
          title: '4. Third-Party Sharing',
          content: '',
          items: ['piLoci follows a Local-first philosophy — all data is stored only on your device.', 'No personal information is transmitted to external servers or third parties.', 'Data is transmitted only when the user explicitly opts into cloud synchronization.'],
        },
        {
          title: '5. Data Destruction',
          content: '',
          items: ['All personal information is destroyed immediately upon account deletion.', 'Passwords are stored only as hashes and cannot be recovered.', 'All user data is permanently deleted upon service termination.'],
        },
        {
          title: '6. Technical and Administrative Safeguards',
          content: '',
          items: ['Passwords: Argon2id one-way hash encryption', 'Authentication: JWT-based session management', 'API access: Project-scoped isolated tokens', 'Network: HTTPS/TLS encrypted communication', 'Database: User and project-level access control'],
        },
        {
          title: '7. Your Rights',
          content: '',
          items: ['You may view, modify, or delete your personal information at any time.', 'Manage directly from the Settings page within the service.', 'For privacy-related inquiries, contact us via email for immediate handling.'],
        },
      ],
      dates: 'Published: January 1, 2026 / Effective: January 1, 2026',
    },
    themeToggle: { toLightAriaLabel: 'Switch to light', toDarkAriaLabel: 'Switch to dark' }
  }
} as const;

export function getCopy(locale: Locale = defaultLocale) {
  return copy[locale];
}
