from __future__ import annotations

"""piloci v0.3 MCP server — 4 tools + 3 resources + 1 prompt.

Core mechanism (copied from supermemory-mcp v4.0):
1. Aggressive tool descriptions push the LLM to call memory/recall.
2. `context` prompt injects "use the memory tool" directive into session.
3. Resources (profile/projects/recent) give LLM passive context without tool calls.
"""

import logging
from typing import Any

import mcp.types as types
import orjson
from mcp.server.lowlevel import Server
from pydantic import AnyUrl, TypeAdapter

from piloci.config import Settings, get_settings
from piloci.storage.embed import embed_one
from piloci.storage.lancedb_store import MemoryStore
from piloci.tools._schema import compact_schema
from piloci.tools.memory_tools import (
    LIST_PROJECTS_DESC,
    MEMORY_DESC,
    RECALL_DESC,
    WHOAMI_DESC,
    ListProjectsInput,
    MemoryInput,
    RecallInput,
    WhoAmIInput,
    handle_list_projects,
    handle_memory,
    handle_recall,
    handle_whoami,
)

logger = logging.getLogger(__name__)

_DEV_USER_ID = "dev-user"
_DEV_PROJECT_ID = "dev-project"


def _make_tool(name: str, description: str, model: type) -> types.Tool:
    schema = model.model_json_schema()
    return types.Tool(
        name=name,
        description=description,
        inputSchema=compact_schema(schema, _top=True),
    )


TOOL_DEFINITIONS = [
    _make_tool("memory", MEMORY_DESC, MemoryInput),
    _make_tool("recall", RECALL_DESC, RecallInput),
    _make_tool("listProjects", LIST_PROJECTS_DESC, ListProjectsInput),
    _make_tool("whoAmI", WHOAMI_DESC, WhoAmIInput),
]


# ---------------------------------------------------------------------------
# Resource URIs
# ---------------------------------------------------------------------------

RESOURCE_PROFILE = "piloci://profile"
RESOURCE_PROJECTS = "piloci://projects"
RESOURCE_RECENT = "piloci://recent"

_RESOURCE_URI_ADAPTER = TypeAdapter(AnyUrl)


def _resource_uri(value: str) -> AnyUrl:
    return _RESOURCE_URI_ADAPTER.validate_python(value)


def _resource_list() -> list[types.Resource]:
    return [
        types.Resource(
            uri=_resource_uri(RESOURCE_PROFILE),
            name="User Profile",
            description="Stable preferences + recent activity (auto-generated by Gemma)",
            mimeType="application/json",
        ),
        types.Resource(
            uri=_resource_uri(RESOURCE_PROJECTS),
            name="Projects",
            description="List of projects available to this user",
            mimeType="application/json",
        ),
        types.Resource(
            uri=_resource_uri(RESOURCE_RECENT),
            name="Recent Memories",
            description="Most recent N memories in the current project",
            mimeType="application/json",
        ),
    ]


# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------

CONTEXT_PROMPT_NAME = "context"

_CONTEXT_DIRECTIVE = (
    "**Important:** Whenever the user shares informative facts, preferences, "
    "personal details, code patterns, decisions, or any memory-worthy "
    "information, use the `memory` tool to save it to piloci. When in doubt, "
    "SAVE. This helps maintain context across conversations."
)


def _build_context_text(profile: dict[str, Any] | None, include_recent: bool = True) -> str:
    parts = [_CONTEXT_DIRECTIVE, ""]

    static = (profile or {}).get("static") or []
    dynamic = (profile or {}).get("dynamic") or []

    if static or (include_recent and dynamic):
        parts.append("## User Context")
    if static:
        parts.append("**Stable Preferences:**")
        parts.extend(f"- {fact}" for fact in static)
    if include_recent and dynamic:
        parts.append("")
        parts.append("**Recent Activity:**")
        parts.extend(f"- {fact}" for fact in dynamic)

    if not static and not dynamic:
        parts.append("")
        parts.append("No user profile yet. Start saving memories to build context.")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Server factory
# ---------------------------------------------------------------------------


def create_mcp_server(
    settings: Settings,
    store: MemoryStore,
    profile_fn=None,
    projects_fn=None,
    recent_fn=None,
) -> Server:
    """Build the MCP server with tools, resources, and prompts registered.

    Args:
        settings: piloci settings
        store: vector store (LanceDB)
        profile_fn: async (user_id, project_id) -> dict | None
                    Returns {"static": [...], "dynamic": [...]}
        projects_fn: async (user_id, refresh: bool) -> list[dict]
        recent_fn: async (user_id, project_id, limit: int) -> list[dict]
    """
    server = Server("piloci")

    async def _embed(text: str) -> list[float]:
        return await embed_one(
            text,
            model=settings.embed_model,
            cache_dir=settings.embed_cache_dir,
            lru_size=settings.embed_lru_size,
            executor_workers=settings.embed_executor_workers,
            max_concurrency=settings.embed_max_concurrency,
        )

    def _get_identity() -> tuple[str, str, dict[str, Any] | None, str | None]:
        """Extract (user_id, project_id, auth_payload, session_id)."""
        from piloci.mcp.session_state import mcp_auth_ctx

        auth = mcp_auth_ctx.get()
        if auth:
            return (
                auth["sub"],
                auth.get("project_id") or _DEV_PROJECT_ID,
                auth,
                auth.get("jti"),
            )
        return (_DEV_USER_ID, _DEV_PROJECT_ID, None, None)

    # -----------------------------------------------------------------------
    # Tools
    # -----------------------------------------------------------------------

    @server.list_tools()
    async def _list_tools() -> list[types.Tool]:
        return TOOL_DEFINITIONS

    @server.call_tool()
    async def _call_tool(name: str, arguments: dict[str, Any]) -> list[types.TextContent]:
        user_id, project_id, auth_payload, session_id = _get_identity()

        if name == "memory":
            args = MemoryInput.model_validate(arguments)
            result = await handle_memory(args, user_id, project_id, store, _embed)
            if result.get("success"):
                from piloci.curator.vault import invalidate_project_vault_cache

                await invalidate_project_vault_cache(
                    get_settings().vault_dir,
                    user_id,
                    project_id,
                    ((auth_payload or {}).get("project_slug") if auth_payload else None),
                )
        elif name == "recall":
            args = RecallInput.model_validate(arguments)
            result = await handle_recall(
                args,
                user_id,
                project_id,
                store,
                _embed,
                profile_fn=profile_fn,
                export_dir=get_settings().export_dir,
            )
        elif name == "listProjects":
            args = ListProjectsInput.model_validate(arguments)
            if projects_fn is None:
                result = {"projects": []}
            else:
                result = await handle_list_projects(args, user_id, projects_fn)
        elif name == "whoAmI":
            args = WhoAmIInput.model_validate(arguments)
            result = await handle_whoami(
                args, user_id, project_id, auth_payload, session_id, client_info=None
            )
        else:
            raise ValueError(f"Unknown tool: {name}")

        from piloci.mcp.session_state import mcp_session_ctx, record_tool_call

        record_tool_call(
            mcp_session_ctx.get(),
            name,
            args.model_dump(exclude_none=True),
        )

        import orjson

        return [types.TextContent(type="text", text=orjson.dumps(result).decode())]

    # -----------------------------------------------------------------------
    # Resources
    # -----------------------------------------------------------------------

    @server.list_resources()
    async def _list_resources() -> list[types.Resource]:
        return _resource_list()

    @server.read_resource()
    async def _read_resource(uri) -> str:
        uri_str = str(uri)
        user_id, project_id, _, _ = _get_identity()

        if uri_str == RESOURCE_PROFILE:
            profile = await profile_fn(user_id, project_id) if profile_fn else None
            return orjson.dumps(profile or {"static": [], "dynamic": []}).decode()

        if uri_str == RESOURCE_PROJECTS:
            projects = await projects_fn(user_id, False) if projects_fn else []
            return orjson.dumps({"projects": projects}).decode()

        if uri_str == RESOURCE_RECENT:
            memories = await recent_fn(user_id, project_id, 20) if recent_fn else []
            return orjson.dumps({"memories": memories}).decode()

        raise ValueError(f"Unknown resource: {uri_str}")

    # -----------------------------------------------------------------------
    # Prompts
    # -----------------------------------------------------------------------

    @server.list_prompts()
    async def _list_prompts() -> list[types.Prompt]:
        return [
            types.Prompt(
                name=CONTEXT_PROMPT_NAME,
                description=(
                    "System context injection: user profile + directive to use "
                    "the memory tool. Load this at session start."
                ),
                arguments=[
                    types.PromptArgument(
                        name="include_recent",
                        description="Include recent activity (default: true)",
                        required=False,
                    ),
                ],
            ),
        ]

    @server.get_prompt()
    async def _get_prompt(name: str, arguments: dict[str, Any] | None) -> types.GetPromptResult:
        if name != CONTEXT_PROMPT_NAME:
            raise ValueError(f"Unknown prompt: {name}")

        user_id, project_id, _, _ = _get_identity()
        args = arguments or {}
        include_recent = args.get("include_recent", True)
        if isinstance(include_recent, str):
            include_recent = include_recent.lower() == "true"

        profile = await profile_fn(user_id, project_id) if profile_fn else None
        text = _build_context_text(profile, include_recent=include_recent)

        return types.GetPromptResult(
            description="piloci user context",
            messages=[
                types.PromptMessage(
                    role="user",
                    content=types.TextContent(type="text", text=text),
                ),
            ],
        )

    return server
